export async function onRequest(context) {
  const response = await context.next();
  const url = new URL(context.request.url);

  // Only enhance the homepage. Every other page remains untouched.
  if (url.pathname !== "/" && url.pathname !== "/index.html") return response;

  const contentType = response.headers.get("content-type") || "";
  if (!contentType.includes("text/html")) return response;

  let html = await response.text();

  // The homepage gallery is generated by home-gallery.js.
  // Remove the old fixed gallery so the dynamic gallery is the only one shown.
  html = html.replace(
    /<section class="section soft reveal" id="activities">[\s\S]*?<\/section>/i,
    ""
  );

  // Keep the navigation clean: text only, no icon.
  html = html.replace(
    /<li><a href="#activities">[\s\S]*?<\/a><\/li>/i,
    '<li><a href="#homepageGallery">صورنا</a></li>'
  );
  html = html.replace(
    /<a href="#activities">[\s\S]*?<\/a>/i,
    '<a href="#homepageGallery">صورنا</a>'
  );

  if (!html.includes('/js/home-gallery.js')) {
    html = html.replace('</body>', '<script src="/js/home-gallery.js" defer></script></body>');
  }

  const headers = new Headers(response.headers);
  headers.set("cache-control", "no-cache, no-store, must-revalidate");
  return new Response(html, { status: response.status, statusText: response.statusText, headers });
}
