export async function onRequest({request}) {
  const html = String.raw`<!doctype html>
<html lang="ar" dir="rtl">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>MedLife | مركز المحتوى</title>
<link rel="icon" href="/logo.PNG">
<style>
body{margin:0;background:#f4f6fa;color:#12203a;font-family:Arial,sans-serif}.wrap{max-width:1000px;margin:auto;padding:20px 14px}.top{display:flex;justify-content:space-between;align-items:center}.logo{height:52px}.card{background:#fff;border:1px solid #e5eaf1;border-radius:18px;padding:16px;margin-top:14px}.login{max-width:430px;margin:50px auto}.field{display:grid;gap:6px;margin:10px 0}.field input,.field select,.field textarea{padding:11px;border:1px solid #e5eaf1;border-radius:10px;font:inherit}.btn{border:0;border-radius:10px;padding:10px 14px;background:#e51f45;color:#fff;font-weight:700;cursor:pointer}.btn.secondary{background:#fff;color:#12203a;border:1px solid #e5eaf1}.btn.green{background:#15966d}.toolbar{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.hidden{display:none!important}.hero{background:#12203a;color:#fff;border-radius:20px;padding:18px;margin-top:14px}.hero p{color:#cbd5e1;font-size:13px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.stat b{display:block;font-size:25px;margin-top:5px}.table{width:100%;border-collapse:collapse}.table th,.table td{padding:10px 7px;border-bottom:1px solid #e5eaf1;text-align:right}.pill{display:inline-block;padding:4px 8px;border-radius:99px;font-size:12px}.high{background:#fff0f2;color:#a31835}.med{background:#fff7dc;color:#806000}.low{background:#edf8f3;color:#126f50}.error{background:#fff3f1;color:#a4261b;border:1px solid #f2c3bd;padding:10px;border-radius:10px;margin-top:10px}.success{background:#eefaf5;color:#126f50;border:1px solid #bfe9d8;padding:10px;border-radius:10px;margin-top:10px}.modal{display:none;position:fixed;inset:0;background:#12203a88;align-items:center;justify-content:center;padding:14px}.modal.open{display:flex}.modalbox{width:min(680px,100%);max-height:90vh;overflow:auto;background:#fff;border-radius:20px;padding:18px}@media(max-width:700px){.top{display:block}.logo{margin-top:10px}.stats{grid-template-columns:1fr 1fr}.table{font-size:12px}}
</style>
</head>
<body><main class="wrap">
<header class="top"><div><small>MEDLIFE CONTENT CENTER 2.0</small><h1>مركز المحتوى</h1><p>بوابة موحّدة لإدارة المحتوى والتنسيق والتصميم.</p></div><img class="logo" src="/logo.PNG" alt="MedLife"></header>
<section id="login" class="card login"><h2>تسجيل الدخول</h2><div class="field"><label>اسم المستخدم</label><input id="username" autocomplete="username"></div><div class="field"><label>كلمة المرور</label><input id="password" type="password" autocomplete="current-password"></div><div class="toolbar"><button class="btn" id="loginBtn">دخول</button><a class="btn secondary" href="/">العودة للموقع</a></div><div id="loginError" class="error hidden"></div></section>
<section id="app" class="hidden"><section class="hero"><h2 id="welcome"></h2><p id="desc"></p><div class="toolbar"><input id="q" placeholder="بحث" class="field input"><select id="status" class="field"><option value="">كل الحالات</option><option>فكرة</option><option>قيد الكتابة</option><option>مراجعة طبية</option><option>قيد التنسيق</option><option>قيد التصميم</option><option>مراجعة نهائية</option><option>جاهز للنشر</option><option>مجدول</option><option>منشور</option></select><button class="btn" id="refresh">تحديث</button><button class="btn secondary" id="logout">خروج</button><button class="btn green hidden" id="newPost">+ إضافة منشور</button><button class="btn secondary hidden" id="addStaff">+ إضافة اسم</button></div></section>
<div class="stats"><div class="card stat"><span>إجمالي</span><b id="total">0</b></div><div class="card stat"><span>أولوية عالية</span><b id="high">0</b></div><div class="card stat"><span>قيد التنفيذ</span><b id="work">0</b></div><div class="card stat"><span>مكتمل</span><b id="done">0</b></div></div>
<section class="card"><div id="error" class="error hidden"></div><div id="success" class="success hidden"></div><div style="overflow:auto"><table class="table"><thead id="thead"></thead><tbody id="rows"></tbody></table></div></section></section></main>
<div id="modal" class="modal"><div class="modalbox"><div class="toolbar"><button class="btn secondary" id="close">إغلاق</button></div><h2 id="modalTitle"></h2><p id="modalSub"></p><div id="modalError" class="error hidden"></div><div id="modalBody"></div></div></div>
<script>
const $=id=>document.getElementById(id);let me=null,items=[];
function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]})}
async function api(url,opt){const r=await fetch(url,Object.assign({credentials:'include',cache:'no-store'},opt||{}));const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'تعذر تنفيذ الطلب');return d}
function show(id,text,ok){const e=$(id);e.textContent=text||'';e.classList.toggle('hidden',!text);if(ok)e.className='success';}
function render(){const q=$('q').value.trim().toLowerCase(),s=$('status').value,d=items.filter(x=>(!q||String(x.title||'').toLowerCase().includes(q))&&(!s||x.status===s));$('total').textContent=items.length;$('high').textContent=items.filter(x=>x.priority==='عالية').length;$('work').textContent=items.filter(x=>!['منشور','جاهز للنشر'].includes(x.status)).length;$('done').textContent=items.filter(x=>x.status==='منشور'||x.formatStatus==='مكتمل'||x.designStatus==='مكتمل').length;let h,r;if(me.type==='cell'){h='<tr><th>العنوان</th><th>الكاتب</th><th>الحالة</th><th>الأولوية</th><th></th></tr>';r=d.map(x=>'<tr><td><strong>'+esc(x.title)+'</strong></td><td>'+esc(x.author||'—')+'</td><td>'+esc(x.status||'—')+'</td><td>'+esc(x.priority||'—')+'</td><td><button class="btn secondary" onclick="openPost(\''+esc(x.id)+'\')">فتح</button></td></tr>').join('')}else if(me.type==='coord'){h='<tr><th>العنوان</th><th>الخلية</th><th>الأولوية</th><th>التنسيق</th><th>المنسق</th><th></th></tr>';r=d.map(x=>'<tr><td><strong>'+esc(x.title)+'</strong></td><td>'+esc(x.cell||'—')+'</td><td>'+esc(x.priority||'—')+'</td><td>'+esc(x.formatStatus||'جديد')+'</td><td>'+esc(x.formatPerson||'—')+'</td><td><button class="btn secondary" onclick="openTask(\''+esc(x.id)+'\',\'format\')">فتح</button></td></tr>').join('')}else{h='<tr><th>العنوان</th><th>الخلية</th><th>الأولوية</th><th>التصميم</th><th>المصمم</th><th></th></tr>';r=d.map(x=>'<tr><td><strong>'+esc(x.title)+'</strong></td><td>'+esc(x.cell||'—')+'</td><td>'+esc(x.priority||'—')+'</td><td>'+esc(x.designStatus||'جديد')+'</td><td>'+esc(x.designPerson||'—')+'</td><td><button class="btn secondary" onclick="openTask(\''+esc(x.id)+'\',\'design\')">فتح</button></td></tr>').join('')}$('thead').innerHTML=h;$('rows').innerHTML=r||'<tr><td colspan="6" style="text-align:center;padding:30px">لا توجد منشورات.</td></tr>'}
async function load(){try{show('error','');const d=await api('/api/content-center-v2?action=list'+($('status').value?'&status='+encodeURIComponent($('status').value):''));items=d.items||[];render()}catch(e){show('error',e.message)}}
function setup(){ $('login').classList.add('hidden');$('app').classList.remove('hidden');$('welcome').textContent=me.type==='cell'?'مركز محتوى '+me.cell:me.type==='coord'?'قسم التنسيق المركزي':me.type==='design'?'قسم التصميم المركزي':'إدارة مركز المحتوى';$('desc').textContent=me.type==='cell'?'إدارة منشورات خليتك وبنكها المعزول.':'منشورات جميع الخلايا، والعمل مستقل عن القسم الآخر.';if(me.type==='cell')$('newPost').classList.remove('hidden');if(me.type==='coord'||me.type==='design')$('addStaff').classList.remove('hidden')}
async function init(){try{const d=await api('/api/content-center-v2?action=me');me=d.identity;setup();await load()}catch(e){}}
$('loginBtn').onclick=async()=>{try{const d=await api('/api/content-center-v2?action=login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:$('username').value,password:$('password').value})});me=d.identity;setup();await load()}catch(e){show('loginError',e.message)}};
$('password').onkeydown=e=>{if(e.key==='Enter')$('loginBtn').click()};$('refresh').onclick=load;$('status').onchange=load;$('q').oninput=render;$('logout').onclick=async()=>{await fetch('/api/content-center-v2?action=logout',{method:'POST',credentials:'include'});location.reload()};$('close').onclick=()=>$('modal').classList.remove('open');
function openModal(t,s,b){$('modalTitle').textContent=t;$('modalSub').textContent=s;$('modalBody').innerHTML=b;$('modal').classList.add('open')}
async function openStaff(type){openModal(type==='design'?'إضافة مصمم':'إضافة منسق','','<div class="field"><label>الاسم الكامل</label><input id="staffName"></div><div class="toolbar"><button class="btn green" id="saveStaff">حفظ الاسم</button></div>');$('saveStaff').onclick=async()=>{try{await api('/api/content-center-v2?action=staff&type='+type,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:$('staffName').value.trim()})});$('modal').classList.remove('open');show('success','تمت إضافة الاسم بنجاح.',true);await load()}catch(e){show('modalError',e.message)}}}
async function openCreate(){openModal('إضافة منشور جديد','بنك '+me.cell,'<div class="field"><label>العنوان *</label><input id="pt"></div><div class="field"><label>كاتب المحتوى *</label><select id="pa"><option>جاري التحميل...</option></select></div><div class="field"><label>الأولوية</label><select id="pp"><option>متوسطة</option><option>عالية</option><option>منخفضة</option></select></div><div class="field"><label>نص المحتوى</label><textarea id="pb"></textarea></div><div class="toolbar"><button class="btn green" id="savePost">حفظ وإرسال</button></div>');try{const d=await api('/api/content-center-v2?action=writers');$('pa').innerHTML='<option value="">اختر الكاتب</option>'+(d.writers||[]).map(x=>'<option value="'+esc(x.name)+'">'+esc(x.name)+'</option>').join('')}catch(e){$('pa').innerHTML='<option>تعذر تحميل القائمة</option>';show('modalError',e.message)}$('savePost').onclick=async()=>{try{if(!$('pt').value.trim()||!$('pa').value)return show('modalError','أدخل العنوان واختر الكاتب.');await api('/api/content-center-v2?action=create',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title:$('pt').value.trim(),author:$('pa').value,priority:$('pp').value,body:$('pb').value})});$('modal').classList.remove('open');show('success','تم حفظ المنشور وإتاحته للتنسيق والتصميم.',true);await load()}catch(e){show('modalError',e.message)}}}
function openPost(id){const x=items.find(v=>v.id===id);if(x)openModal(x.title,'', '<div class="card">الكاتب: '+esc(x.author||'—')+'<br>الأولوية: '+esc(x.priority||'—')+'<br>الحالة: '+esc(x.status||'—')+'</div>')}
async function openTask(id,kind){const x=items.find(v=>v.id===id);if(!x)return;try{const d=await api('/api/content-center-v2?action=staff&type='+(kind==='design'?'design':'coord'));const label=kind==='design'?'المصمم':'المنسق';openModal(kind==='design'?'إنجاز مهمة التصميم':'إنجاز مهمة التنسيق',x.title,'<div class="field"><label>'+label+'</label><select id="person"><option value="">اختر الاسم</option>'+(d.staff||[]).map(s=>'<option value="'+esc(s.name)+'">'+esc(s.name)+'</option>').join('')+'</select></div><div class="field"><label>التقييم 1–10</label><input id="rating" type="number" min="1" max="10"></div><div class="field"><label>سرعة الأداء 1–10</label><input id="speed" type="number" min="1" max="10"></div>'+(kind==='format'?'<div class="field"><label>التفاعل 1–10</label><input id="interaction" type="number" min="1" max="10"></div>':'')+'<div class="toolbar"><button class="btn green" id="complete">تم الإنجاز</button></div>');$('complete').onclick=async()=>{try{if(!$('person').value||!$('rating').value)return show('modalError','اختر الاسم وأدخل التقييم.');await api('/api/content-center-v2?action='+kind,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({page_id:id,person:$('person').value,rating:$('rating').value,speed:$('speed').value,interaction:$('interaction')?$('interaction').value:''})});$('modal').classList.remove('open');show('success','تم تسجيل المهمة والتقييم.',true);await load()}catch(e){show('modalError',e.message)}}}catch(e){show('error',e.message)}}
$('newPost').onclick=openCreate;$('addStaff').onclick=()=>openStaff(me.type);init();
</script></body></html>`;
  return new Response(html,{headers:{"content-type":"text/html;charset=utf-8","cache-control":"no-store,no-cache,must-revalidate,max-age=0"}});
}
