(() => {
  const items = [['index.html','الرئيسية'],['about-medlife.html','عن المؤسسة'],['#programs','مجالات العمل'],['index.html#homepageGallery','صورنا'],['articles.html','المقالات'],['forum-v3.html','المنتدى'],['support.html','صندوق الدعم'],['contact.html','تواصل معنا']];
  const current = location.pathname.split('/').pop() || 'index.html';
  const isHome = current === 'index.html' || current === '';
  const href = target => target.startsWith('#') ? (isHome ? target : `index.html${target}`) : target;
  function buildNav(){
    let header=document.querySelector('header');
    if(!header){header=document.createElement('header');document.body.prepend(header)}
    header.innerHTML=`<div class="medlife-nav-wrap"><a class="medlife-brand" href="index.html" aria-label="مؤسسة ميدلايف"><img src="/logo.PNG" alt="مؤسسة ميدلايف" class="medlife-logo"></a><nav class="medlife-nav-links" aria-label="التنقل الرئيسي">${items.map(([target,label])=>{const url=href(target);const active=(target==='index.html'&&isHome)||(target!=='index.html'&&!target.startsWith('#')&&current===target);return `<a class="${active?'active':''} ${label==='صندوق الدعم'?'support-link':''}" href="${url}">${label}</a>`}).join('')}</nav><div class="medlife-actions"><a class="medlife-login" href="login.html">دخول الأعضاء</a><a class="medlife-join" href="join-options.html">الانضمام إلى ميدلايف</a></div><button class="medlife-menu" type="button" aria-label="فتح القائمة" aria-expanded="false">القائمة</button></div><div class="medlife-mobile" hidden><div class="medlife-mobile-inner">${items.map(([target,label])=>`<a href="${href(target)}">${label}</a>`).join('')}<a href="login.html">دخول الأعضاء</a><a href="join-options.html">الانضمام إلى ميدلايف</a></div></div>`;
    if(!document.getElementById('medlife-nav-style')){const style=document.createElement('style');style.id='medlife-nav-style';style.textContent=`header.medlife-header,header{position:sticky;top:0;z-index:2000;background:rgba(255,255,255,.96);backdrop-filter:blur(16px);border-bottom:1px solid #e2e8f0}.medlife-nav-wrap{width:min(1280px,calc(100% - 30px));min-height:76px;margin:auto;display:flex;align-items:center;gap:18px}.medlife-brand{margin-inline-end:auto;display:flex;align-items:center}.medlife-logo{height:50px;width:auto;display:block}.medlife-nav-links{display:flex;align-items:center;gap:15px;flex-wrap:wrap}.medlife-nav-links a{color:#151d36;text-decoration:none;font:800 11.5px Cairo,sans-serif;padding:8px 2px;white-space:nowrap;transition:.2s}.medlife-nav-links a:hover,.medlife-nav-links a.active{color:#ff2a54}.medlife-nav-links a.support-link{color:#ff2a54}.medlife-actions{display:flex;align-items:center;gap:7px}.medlife-actions a{font:800 11px Cairo,sans-serif;text-decoration:none;white-space:nowrap;border-radius:11px;padding:8px 11px}.medlife-login{border:1px solid #e2e8f0;color:#151d36;background:#fff}.medlife-join{background:#ff2a54;color:#fff}.medlife-menu{display:none;border:1px solid #e2e8f0;background:#f6f8fc;color:#151d36;border-radius:12px;padding:9px 13px;font:800 12px Cairo,sans-serif;cursor:pointer}.medlife-mobile{border-top:1px solid #e2e8f0;background:#fff}.medlife-mobile-inner{width:min(1180px,calc(100% - 30px));margin:auto;display:grid}.medlife-mobile a{color:#151d36;text-decoration:none;font:800 13px Cairo,sans-serif;padding:12px 4px;border-bottom:1px solid #eef2f7}@media(max-width:1180px){.medlife-nav-links{gap:10px}.medlife-nav-links a{font-size:11px}.medlife-actions{display:none}.medlife-menu{display:block}}`;document.head.appendChild(style)}
    header.classList.add('medlife-header');const menu=header.querySelector('.medlife-menu');const mobile=header.querySelector('.medlife-mobile');menu.addEventListener('click',()=>{const open=!mobile.hidden;mobile.hidden=open;menu.setAttribute('aria-expanded',String(!open))});mobile.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{mobile.hidden=true}));
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',buildNav);else buildNav();
})();
