(() => {
  const items = [['index.html','الرئيسية','home'],['about-medlife.html','عن المؤسسة','about'],['index.html#programs','مجالات العمل','programs'],['index.html#homepageGallery','صورنا','gallery'],['articles.html','المقالات','articles'],['forum-v3.html','المنتدى','forum'],['support.html','صندوق الدعم','support'],['contact.html','تواصل معنا','contact']];
  const page=location.pathname.split('/').pop()||'index.html', home=page===''||page==='index.html';
  const activeKey=()=>{if(page==='gallery.html')return'gallery';if(home&&location.hash==='#programs')return'programs';if(home&&location.hash==='#homepageGallery')return'gallery';if(home)return'home';const m=items.find(x=>x[0].split('#')[0]===page&&!x[0].includes('#'));return m?m[2]:''};
  const setActive=k=>document.querySelectorAll('.medlife-global-nav a,.medlife-global-mobile a').forEach(a=>a.classList.toggle('active',a.dataset.key===k));
  function build(){
    document.querySelectorAll('header').forEach(h=>h.remove());
    const current=activeKey(),header=document.createElement('header');header.className='medlife-global-header';
    header.innerHTML=`<div class="medlife-global-wrap"><a class="medlife-global-brand" href="index.html" aria-label="مؤسسة ميدلايف"><img src="/logo.PNG" alt="مؤسسة ميدلايف"></a><nav class="medlife-global-nav" aria-label="التنقل الرئيسي">${items.map(([u,l,k])=>`<a href="${u}" data-key="${k}" class="${k===current?'active':''}">${l}</a>`).join('')}</nav><div class="medlife-global-actions"><a href="login.html">دخول الأعضاء</a><a class="join" href="join-options.html">الانضمام</a></div><button class="medlife-global-menu" type="button" aria-label="فتح القائمة" aria-expanded="false">القائمة</button></div><div class="medlife-global-mobile" hidden>${items.map(([u,l,k])=>`<a href="${u}" data-key="${k}" class="${k===current?'active':''}">${l}</a>`).join('')}<a href="login.html">دخول الأعضاء</a><a href="join-options.html">الانضمام إلى ميدلايف</a></div>`;
    document.body.prepend(header);
    if(!document.getElementById('medlife-global-nav-style')){const s=document.createElement('style');s.id='medlife-global-nav-style';s.textContent=`.medlife-global-header{position:sticky;top:0;z-index:2500;background:rgba(255,255,255,.96);backdrop-filter:blur(18px);border-bottom:1px solid #e2e8f0;box-shadow:0 8px 28px rgba(21,29,54,.06)}.medlife-global-wrap{width:min(1240px,calc(100% - 30px));min-height:78px;margin:auto;display:flex;align-items:center;gap:22px}.medlife-global-brand{margin-inline-end:auto;display:flex;align-items:center}.medlife-global-brand img{height:50px;width:auto;display:block}.medlife-global-nav{display:flex;align-items:stretch;gap:3px;min-height:78px}.medlife-global-nav a{position:relative;display:flex;align-items:center;padding:0 10px;color:#151d36;text-decoration:none;font:800 12px Cairo,sans-serif;white-space:nowrap;transition:color .25s ease,transform .25s ease}.medlife-global-nav a::after{content:"";position:absolute;left:10px;right:10px;bottom:12px;height:3px;border-radius:99px;background:#ff2a54;transform:scaleX(0);transition:transform .25s ease}.medlife-global-nav a:hover{color:#ff2a54;transform:translateY(-1px)}.medlife-global-nav a.active{color:#ff2a54}.medlife-global-nav a.active::after{transform:scaleX(1)}.medlife-global-actions{display:flex;gap:7px;align-items:center}.medlife-global-actions a{border:1px solid #e2e8f0;border-radius:11px;padding:8px 11px;color:#151d36;text-decoration:none;font:800 11px Cairo,sans-serif;white-space:nowrap;transition:.25s}.medlife-global-actions a:hover{border-color:#ff2a54;color:#ff2a54;transform:translateY(-2px)}.medlife-global-actions .join{background:#ff2a54;border-color:#ff2a54;color:#fff}.medlife-global-menu{display:none;border:1px solid #e2e8f0;background:#f6f8fc;color:#151d36;border-radius:11px;padding:9px 13px;font:800 12px Cairo,sans-serif;cursor:pointer}.medlife-global-mobile{border-top:1px solid #e2e8f0;background:#fff}.medlife-global-mobile a{display:block;padding:12px 18px;border-bottom:1px solid #eef2f7;color:#151d36;text-decoration:none;font:800 13px Cairo,sans-serif}.medlife-global-mobile a.active{color:#ff2a54;background:#fff7f9;border-inline-start:3px solid #ff2a54}@media(max-width:1180px){.medlife-global-nav,.medlife-global-actions{display:none}.medlife-global-menu{display:block}}`;document.head.appendChild(s)}
    const menu=header.querySelector('.medlife-global-menu'),mobile=header.querySelector('.medlife-global-mobile');menu.addEventListener('click',()=>{const open=!mobile.hidden;mobile.hidden=open;menu.setAttribute('aria-expanded',String(!open))});mobile.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>mobile.hidden=true));
    if(home&&'IntersectionObserver'in window){const observer=new IntersectionObserver(es=>{const v=es.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(v)setActive(v.target.id==='programs'?'programs':'gallery');else if(!location.hash)setActive('home')},{rootMargin:'-30% 0px -55% 0px',threshold:[0,.2,.5]});['programs','homepageGallery'].forEach(id=>{const el=document.getElementById(id);if(el)observer.observe(el)})}
  }
  window.addEventListener('hashchange',()=>setActive(activeKey()));
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',build);else build();
})();
