(() => {
  const items = [['index.html','الرئيسية'],['about-medlife.html','عن المؤسسة'],['index.html#programs','مجالات العمل'],['index.html#homepageGallery','صورنا'],['articles.html','المقالات'],['forum-v3.html','المنتدى'],['support.html','صندوق الدعم'],['contact.html','تواصل معنا']];
  const current = location.pathname.split('/').pop() || 'index.html';
  const isHome = current === 'index.html' || current === '';
  const isActive = target => { const page = target.split('#')[0]; if(page==='index.html') return isHome && !target.includes('#'); return current===page; };
  function buildNav(){
    const old=document.querySelector('header.medlife-site-header'); if(old) old.remove();
    const header=document.createElement('header'); header.className='medlife-site-header';
    header.innerHTML=`<div class="medlife-nav-wrap"><a class="medlife-brand" href="index.html"><img src="/logo.PNG" alt="مؤسسة ميدلايف"></a><nav class="medlife-nav" aria-label="التنقل الرئيسي">${items.map(([target,label])=>`<a class="${isActive(target)?'active':''} ${label==='صندوق الدعم'?'support':''}" href="${target}">${label}</a>`).join('')}</nav><div class="medlife-actions"><a href="login.html">دخول الأعضاء</a><a href="join-options.html">الانضمام</a></div><button class="medlife-menu" type="button" aria-label="فتح القائمة" aria-expanded="false">القائمة</button></div><div class="medlife-mobile" hidden>${items.map(([target,label])=>`<a class="${isActive(target)?'active':''}" href="${target}">${label}</a>`).join('')}<a href="login.html">دخول الأعضاء</a><a href="join-options.html">الانضمام</a></div>`;
    document.body.prepend(header);
    if(!document.getElementById('medlife-site-nav-style')){const style=document.createElement('style');style.id='medlife-site-nav-style';style.textContent=`.medlife-site-header{position:sticky;top:0;z-index:2500;background:rgba(255,255,255,.94);backdrop-filter:blur(18px);border-bottom:1px solid #e2e8f0;box-shadow:0 8px 28px rgba(21,29,54,.06)}.medlife-nav-wrap{width:min(1220px,calc(100% - 30px));min-height:78px;margin:auto;display:flex;align-items:center;gap:24px}.medlife-brand{margin-inline-end:auto;display:flex;align-items:center}.medlife-brand img{height:50px;width:auto;display:block}.medlife-nav{display:flex;align-items:stretch;gap:4px;height:78px}.medlife-nav a{position:relative;display:flex;align-items:center;padding:0 10px;color:#151d36;text-decoration:none;font:800 12px Cairo,sans-serif;white-space:nowrap;transition:color .25s}.medlife-nav a:after{content:"";position:absolute;left:10px;right:10px;bottom:13px;height:3px;border-radius:99px;background:#ff2a54;transform:scaleX(0);transition:transform .25s}.medlife-nav a:hover,.medlife-nav a.active{color:#ff2a54}.medlife-nav a.active:after{transform:scaleX(1)}.medlife-actions{display:flex;gap:7px;align-items:center}.medlife-actions a{border:1px solid #e2e8f0;border-radius:11px;padding:8px 11px;color:#151d36;text-decoration:none;font:800 11px Cairo,sans-serif;white-space:nowrap;transition:.25s}.medlife-actions a:hover{border-color:#ff2a54;color:#ff2a54;transform:translateY(-2px)}.medlife-menu{display:none;border:1px solid #e2e8f0;background:#f6f8fc;color:#151d36;border-radius:11px;padding:9px 13px;font:800 12px Cairo,sans-serif;cursor:pointer}.medlife-mobile{border-top:1px solid #e2e8f0;background:#fff}.medlife-mobile a{display:block;padding:12px 18px;border-bottom:1px solid #eef2f7;color:#151d36;text-decoration:none;font:800 13px Cairo,sans-serif}.medlife-mobile a.active{color:#ff2a54;background:#fff7f9;border-inline-start:3px solid #ff2a54}@media(max-width:1150px){.medlife-nav,.medlife-actions{display:none}.medlife-menu{display:block}}`;document.head.appendChild(style)}
    const menu=header.querySelector('.medlife-menu'),mobile=header.querySelector('.medlife-mobile');menu.addEventListener('click',()=>{const open=!mobile.hidden;mobile.hidden=open;menu.setAttribute('aria-expanded',String(!open))});
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',buildNav);else buildNav();
})();
