/* MedLife — Support Us interactive section */
(function(){'use strict';
const css=`.ml-support{max-width:1120px;margin:80px auto;padding:24px}.ml-support-box{position:relative;overflow:hidden;border-radius:30px;padding:42px;background:linear-gradient(135deg,#071b3a,#123e69);color:#fff;box-shadow:0 24px 70px rgba(7,27,58,.22)}.ml-support-box:before,.ml-support-box:after{content:'';position:absolute;border-radius:50%;background:rgba(255,255,255,.07);pointer-events:none}.ml-support-box:before{width:330px;height:330px;right:-120px;top:-150px}.ml-support-box:after{width:220px;height:220px;left:-100px;bottom:-120px}.ml-support-head{position:relative;z-index:1;text-align:center;max-width:760px;margin:auto}.ml-support-head h2{font-size:clamp(30px,5vw,48px);margin:0 0 12px}.ml-support-head p{line-height:1.9;opacity:.9}.ml-support-step{position:relative;z-index:1;margin-top:30px}.ml-support-step h3{margin:0 0 14px}.ml-support-options{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.ml-support-option{border:1px solid rgba(255,255,255,.2);background:rgba(255,255,255,.08);color:#fff;border-radius:16px;padding:16px 10px;cursor:pointer;transition:.25s;font:inherit}.ml-support-option:hover,.ml-support-option.active{transform:translateY(-4px);background:rgba(255,255,255,.18);border-color:#fff}.ml-support-methods{display:grid;grid-template-columns:repeat(5,1fr);gap:12px}.ml-method{border:1px solid rgba(255,255,255,.2);background:rgba(255,255,255,.08);color:#fff;border-radius:16px;padding:16px 8px;cursor:pointer;transition:.25s;font:inherit}.ml-method:hover,.ml-method.active{transform:translateY(-4px);background:rgba(255,255,255,.18);border-color:#fff}.ml-support-details{display:none;margin-top:18px;padding:22px;border-radius:20px;background:rgba(255,255,255,.1);backdrop-filter:blur(8px)}.ml-support-details.show{display:block;animation:mlFade .35s ease}.ml-support-detail-row{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:10px 0;border-bottom:1px solid rgba(255,255,255,.12)}.ml-support-detail-row:last-child{border-bottom:0}.ml-copy{border:0;border-radius:10px;padding:8px 12px;cursor:pointer;font-weight:700}.ml-support-note{font-size:13px;opacity:.75;margin-top:12px}@keyframes mlFade{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:none}}@media(max-width:850px){.ml-support-options{grid-template-columns:repeat(2,1fr)}.ml-support-methods{grid-template-columns:repeat(2,1fr)}}@media(max-width:520px){.ml-support{padding:14px}.ml-support-box{padding:28px 18px}.ml-support-options,.ml-support-methods{grid-template-columns:1fr}.ml-support-detail-row{align-items:flex-start;flex-direction:column}}`;
const s=document.createElement('style');s.textContent=css;document.head.appendChild(s);
const target=document.querySelector('main')||document.body;const sec=document.createElement('section');sec.className='ml-support';sec.id='support-medlife';
sec.innerHTML=`<div class="ml-support-box"><div class="ml-support-head"><div style="font-size:46px">❤️</div><h2>ادعم مؤسسة ميدلايف</h2><p>مساهمتك تساعدنا على الاستمرار في تنفيذ المبادرات الطبية والتعليمية والمجتمعية ودعم الأطفال والشباب وتعزيز ثقافة التطوع.</p></div><div class="ml-support-step"><h3>1. اختر المجال الذي ترغب بدعمه</h3><div class="ml-support-options"><button class="ml-support-option" data-area="الحملات الطبية">🩺 الحملات الطبية</button><button class="ml-support-option" data-area="دعم الأطفال">👶 دعم الأطفال</button><button class="ml-support-option" data-area="المبادرات المدرسية">🏫 المبادرات المدرسية</button><button class="ml-support-option" data-area="الحملات الرمضانية">🌙 الحملات الرمضانية</button><button class="ml-support-option" data-area="منتدى ميدلايف">📚 منتدى ميدلايف</button><button class="ml-support-option" data-area="العمل التطوعي">🤝 العمل التطوعي</button><button class="ml-support-option" data-area="دعم عام">💙 دعم عام</button></div></div><div class="ml-support-step"><h3>2. اختر طريقة التحويل</h3><div class="ml-support-methods"><button class="ml-method" data-method="شركة الهرم">🏢 شركة الهرم</button><button class="ml-method" data-method="سيرياتيل كاش">📱 سيرياتيل كاش</button><button class="ml-method" data-method="MTN كاش">📱 MTN كاش</button><button class="ml-method" data-method="شام كاش">📲 شام كاش</button><button class="ml-method" data-method="بنك الشرق">🏦 بنك الشرق</button></div><div class="ml-support-details" id="mlSupportDetails"></div><div class="ml-support-note">يرجى التأكد من بيانات التحويل قبل تنفيذ العملية. التبرع يتم مباشرة عبر وسيلة التحويل التي تختارها.</div></div></div>`;target.appendChild(sec);
const details={
'شركة الهرم':{label:'مؤسسة ميدلايف الطبية الخيرية التطوعية',value:'0998942124',kind:'رقم الموبايل'},
'سيرياتيل كاش':{label:'رمز سيرياتيل كاش',value:'00497549',kind:'الرمز'},
'MTN كاش':{label:'رمز MTN كاش',value:'4524-0602-1501-8298',kind:'الرمز'},
'شام كاش':{label:'معرّف شام كاش',value:'4499163b0ffadf3a240bb95c1079c674',kind:'المعرّف'},
'بنك الشرق':{label:'رقم حساب بنك الشرق',value:'5557977',kind:'رقم الحساب'}
};
let area='';sec.querySelectorAll('.ml-support-option').forEach(b=>b.addEventListener('click',()=>{sec.querySelectorAll('.ml-support-option').forEach(x=>x.classList.remove('active'));b.classList.add('active');area=b.dataset.area;}));
sec.querySelectorAll('.ml-method').forEach(b=>b.addEventListener('click',()=>{sec.querySelectorAll('.ml-method').forEach(x=>x.classList.remove('active'));b.classList.add('active');const d=details[b.dataset.method];const box=sec.querySelector('#mlSupportDetails');box.innerHTML=`<div class="ml-support-detail-row"><strong>${d.label}</strong><span>${d.value}</span><button class="ml-copy" type="button">نسخ</button></div><div style="margin-top:10px;opacity:.8">المجال المختار: ${area||'دعم عام'}</div>`;box.classList.add('show');box.querySelector('.ml-copy').onclick=async()=>{try{await navigator.clipboard.writeText(d.value);box.querySelector('.ml-copy').textContent='تم النسخ ✓'}catch(e){box.querySelector('.ml-copy').textContent='انسخ الرقم يدوياً'}};}));
})();