name = "medlife-articles-api"
main = "workers/articles-api/worker.js"
compatibility_date = "2026-01-01"

[[d1_databases]]
binding = "DB"
database_name = "medlife-articles"
database_id = "036972c6-162c-47d9-9fea-d011cb451da7"

[ai]
binding = "AI"
