const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET,POST,PUT,PATCH,DELETE,OPTIONS","Access-Control-Allow-Headers":"Content-Type, Authorization"};
const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{"Content-Type":"application/json",...corsHeaders}});
const auth=(r,e)=>!!e.ADMIN_API_KEY&&r.headers.get("Authorization")==`Bearer ${e.ADMIN_API_KEY}`;
const aiPrompt=(mode,a)=>{const title=a?.title_ar||"",content=a?.content_ar||"",category=a?.category||"";const base=`أنت محرر طبي محترف لمؤسسة MedLife الطبية. تعامل مع النص كمادة تثقيفية طبية، ولا تخترع مراجع أو أرقاماً أو توصيات علاجية. حسّن اللغة والأسلوب مع الحفاظ على المعنى، ونبّه إلى أي معلومة طبية تحتاج مراجعة بشرية. المقال بالعربية، والتصنيف: ${category}. العنوان: ${title}.\n\nالمحتوى:\n${content}`;if(mode==="visual")return `${base}\n\nحلل المقال بصرياً واقترح حتى 5 صور مفيدة وغير زخرفية. أعد JSON فقط بهذا الشكل: {"image_suggestions":[{"type":"cover|illustration|infographic","description":"وصف الصورة بالعربية","prompt":"وصف جاهز لتوليد صورة طبية احترافية وغير دموية","position":"cover|after_intro|section_2|section_3|inside"}]}. لا تقترح صوراً تشخّص أشخاصاً حقيقيين ولا صوراً دموية.`;return `${base}\n\nأعد JSON فقط بهذا الشكل: {"title_ar":"عنوان احترافي","excerpt_ar":"ملخص جذاب من 2-3 جمل","seo_title":"عنوان SEO","seo_description":"وصف SEO","toc":["..."],"content_ar":"النص بعد التدقيق والتنظيم بعناوين واضحة","medical_notes":["ملاحظات تحتاج مراجعة بشرية"]}. اجعل الصياغة رسمية، عربية سليمة، والمصطلحات الطبية دقيقة.`};
const parseAI=x=>{if(typeof x==="string")return x;return x?.response??x?.result??x};
export default{async fetch(req,env){if(req.method==="OPTIONS")return new Response(null,{headers:corsHeaders});const u=new URL(req.url),p=u.pathname.split('/').filter(Boolean);try{
if(p[0]==="api"&&p[1]==="article-ai"){if(req.method!=="POST")return json({error:"Method not allowed"},405);if(!auth(req,env))return json({error:"Unauthorized"},401);if(!env.AI)return json({error:"Workers AI binding 'AI' is not configured"},503);const b=await req.json();const mode=b.mode||"analyze";const prompt=aiPrompt(mode,b.article||{});const response=await env.AI.run("@cf/meta/llama-3.1-8b-instruct-fast",{messages:[{role:"system",content:"You are MedLife's professional medical editorial assistant. Output valid JSON only when requested."},{role:"user",content:prompt}],max_tokens:mode==="visual"?1800:6000,temperature:0.2});let raw=parseAI(response);let result=raw;try{if(typeof raw==="string"){const m=raw.match(/\{[\s\S]*\}/);result=JSON.parse(m?m[0]:raw)}}catch{result={raw}}return json({success:true,mode,result},200)}
if(p[0]==="public"&&p[1]==="articles"){if(req.method!=="GET")return json({error:"Method not allowed"},405);if(p[2])return json(await env.DB.prepare("SELECT id,title_ar,title_en,excerpt_ar,excerpt_en,content_ar,content_en,author_name,category,image_url,created_at,updated_at FROM articles WHERE slug=? AND status='published'").bind(p[2]).first());return json((await env.DB.prepare("SELECT id,title_ar,title_en,excerpt_ar,excerpt_en,author_name,category,image_url,created_at,updated_at FROM articles WHERE status='published' ORDER BY created_at DESC").all()).results)}
if(p[0]==="articles"){if(!auth(req,env))return json({error:"Unauthorized: invalid or missing ADMIN_API_KEY"},401);
if(p.length===1&&req.method==="GET")return json((await env.DB.prepare("SELECT * FROM articles ORDER BY created_at DESC").all()).results);
if(p.length===1&&req.method==="POST"){let b=await req.json();let r=await env.DB.prepare("INSERT INTO articles (title_ar,title_en,excerpt_ar,excerpt_en,content_ar,content_en,author_name,author_email,category,image_url,status) VALUES (?,?,?,?,?,?,?,?,?,?,?)").bind(b.title_ar,b.title_en,b.excerpt_ar,b.excerpt_en,b.content_ar,b.content_en,b.author_name,b.author_email,b.category,b.image_url,b.status||"pending").run();return json(await env.DB.prepare("SELECT * FROM articles WHERE id=?").bind(r.meta.last_row_id).first(),201)}
if(p[1]&&req.method==="DELETE"){await env.DB.prepare("DELETE FROM articles WHERE id=?").bind(p[1]).run();return json({success:true})}
if(p[1]&&req.method==="PUT"){let b=await req.json();await env.DB.prepare("UPDATE articles SET title_ar=?,title_en=?,excerpt_ar=?,excerpt_en=?,content_ar=?,content_en=?,author_name=?,author_email=?,category=?,image_url=?,status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(b.title_ar,b.title_en,b.excerpt_ar,b.excerpt_en,b.content_ar,b.content_en,b.author_name,b.author_email,b.category,b.image_url,b.status,p[1]).run();return json(await env.DB.prepare("SELECT * FROM articles WHERE id=?").bind(p[1]).first())}
if(p[1]&&p[2]==="status"&&req.method==="PATCH"){let b=await req.json();await env.DB.prepare("UPDATE articles SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(b.status,p[1]).run();return json(await env.DB.prepare("SELECT * FROM articles WHERE id=?").bind(p[1]).first())}}
return json({error:"Not found"},404)}catch(e){return json({error:e.message},500)}}};