const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET,POST,PUT,PATCH,DELETE,OPTIONS","Access-Control-Allow-Headers":"Content-Type, Authorization"};
const COOKIE='medlife_articles_session';const enc=new TextEncoder();
const json=(d,s=200,extra={})=>new Response(JSON.stringify(d),{status:s,headers:{"Content-Type":"application/json; charset=UTF-8","Cache-Control":"no-store",...corsHeaders,...extra}});
function hex(bytes){return Array.from(new Uint8Array(bytes)).map(b=>b.toString(16).padStart(2,'0')).join('');}async function sha256(v){return hex(await crypto.subtle.digest('SHA-256',enc.encode(v)));}
function getCookie(req,name){const raw=req.headers.get('Cookie')||'';for(const part of raw.split(';')){const p=part.trim();if(p.startsWith(name+'='))return decodeURIComponent(p.slice(name.length+1));}return null;}
async function sessionAuth(req,env){if(!env.DB)return null;try{const token=getCookie(req,COOKIE);if(!token)return null;const hash=await sha256(token);const row=await env.DB.prepare(`SELECT a.id account_id,a.member_id,a.username,a.role,a.account_status FROM member_sessions s JOIN member_accounts a ON a.id=s.account_id WHERE s.token_hash=? AND datetime(s.expires_at)>datetime('now') LIMIT 1`).bind(hash).first();if(!row||row.account_status!=='active')return null;if(!['admin','editor','reviewer'].includes(String(row.role||'').toLowerCase()))return null;return row;}catch{return null;}}
function aiPrompt(action,a){const title=a?.title||a?.title_ar||'',content=a?.content||a?.content_ar||'',category=a?.category||'',author=a?.author_name||'';const rules=`أنت رئيس تحرير طبي محترف لمؤسسة MedLife. حرر المقال الموجود فقط. ممنوع اختصاره أو حذف أي معلومة علمية أو رقم أو نسبة أو مدة أو اسم دواء أو تحذير أو مصدر، وممنوع تغيير المعنى أو اختراع معلومات. صحح اللغة، رتب الفقرات، أنشئ عناوين وفهرسًا، وحوّل القوائم إلى نقاط أو جداول عند الحاجة. إذا احتاجت معلومة تحققًا احتفظ بها وأضفها إلى editor_notes. اجعل العربية رسمية وطبية وواضحة وممتعة للويب. الكاتب: ${author}. التصنيف: ${category}. العنوان: ${title}. النص الكامل: ---BEGIN ARTICLE---${content}---END ARTICLE---`;
if(action==='visual')return `${rules}\nحدد حتى 5 مواضع للصور. لكل صورة أعطني query إنجليزيًا دقيقًا للبحث في Wikimedia Commons، وplacement وpurpose وalt_text. الأولوية لغلاف ثم صور تعليمية/infographic، وتجنب الدم أو الصدمة. JSON فقط: {"image_suggestions":[{"type":"cover|illustration|infographic","placement":"...","purpose":"...","query":"...","alt_text":"..."}],"editor_notes":["..."]}`;
if(action==='seo')return `${rules}\nلا تعدل المحتوى. JSON فقط: {"excerpt":"ملخص 2-4 جمل دون معلومات جديدة","seo":{"title":"...","description":"...","keywords":["..."]},"editor_notes":["..."]}`;
const task=action==='medical'?'دقق المصطلحات الطبية والصياغة مع الحفاظ الكامل على النص.':action==='proofread'?'دقق اللغة والإملاء والترقيم فقط مع الحفاظ الكامل على المعلومات.':action==='format'?'نظم المقال وفهرسه وأنشئ عناوين وقوائم وجداول عند الحاجة مع الحفاظ على كامل المحتوى.':'أعد تحرير المقال ليصبح احترافيًا عالمي المستوى مع الحفاظ على كامل المحتوى العلمي دون اختصار.';return `${rules}\n${task}\nJSON فقط: {"title":"...","excerpt":"...","content_ar":"النص الكامل بعد التحرير دون حذف","toc":[{"title":"..."}],"seo":{"title":"...","description":"...","keywords":["..."]},"image_suggestions":[{"type":"cover|illustration|infographic","placement":"...","purpose":"...","query":"...","alt_text":"..."}],"editor_notes":["..."],"polish_score":0}`;}
function parseAI(x){const raw=typeof x==='string'?x:(x?.response??x?.result??x?.choices?.[0]?.message?.content??'');if(typeof raw!=='string')return raw;const m=raw.match(/\{[\s\S]*\}/);try{return JSON.parse(m?m[0]:raw)}catch{return {raw}}}
function numericTokens(s){return String(s||'').match(/\b\d+(?:[.,]\d+)?\b/g)||[];}function validatePreservation(o,r){const src=String(o||'').trim(),out=String(r?.content_ar||'').trim();if(!out)return {ok:false,reason:'لم تُنتج نسخة كاملة من المقال.'};if(out.length<src.length*.82)return {ok:false,reason:'النسخة المقترحة أقصر بشكل غير آمن؛ تم إيقافها لحماية المحتوى العلمي.'};const missing=[...new Set(numericTokens(src))].filter(n=>!new Set(numericTokens(out)).has(n));if(missing.length)return {ok:false,reason:'تم فقد أرقام من النص الأصلي: '+missing.slice(0,12).join('، ')};return {ok:true};}
function normalize(action,r,o){if(action==='visual')return {image_suggestions:(r?.image_suggestions||[]).slice(0,5),editor_notes:r?.editor_notes||[]};if(action==='seo')return r||{};const c=validatePreservation(o,r);if(!c.ok)throw Error(c.reason);return r||{};}
function slug(v){return String(v||'article').toLowerCase().replace(/[^a-z0-9\u0600-\u06ff]+/g,'-').replace(/^-+|-+$/g,'').slice(0,70)||'article';}
async function uniqueSlug(db,title,id=null){const base=slug(title);let candidate=base;for(let i=0;i<20;i++){const row=id?await db.prepare('SELECT id FROM articles WHERE slug=? AND id<>? LIMIT 1').bind(candidate,id).first():await db.prepare('SELECT id FROM articles WHERE slug=? LIMIT 1').bind(candidate).first();if(!row)return candidate;candidate=`${base}-${crypto.randomUUID().slice(0,8)}`;}return `${base}-${Date.now().toString(36)}`;}
async function ensureSlugColumn(db){try{await db.prepare('ALTER TABLE articles ADD COLUMN slug TEXT').run();}catch(e){if(!String(e?.message||e).toLowerCase().includes('duplicate column'))throw e;}}
function b64(bytes){let s='';const a=new Uint8Array(bytes);for(let i=0;i<a.length;i+=0x8000)s+=String.fromCharCode(...a.subarray(i,i+0x8000));return btoa(s);}
async function githubPut(env,path,bytes){if(!env.GITHUB_CONTENTS_TOKEN)throw Error('GITHUB_CONTENTS_TOKEN غير مهيأ على Worker.');const u=`https://api.github.com/repos/Medlifesy/medlife-website/contents/${path.split('/').map(encodeURIComponent).join('/')}`;const r=await fetch(u,{method:'PUT',headers:{Authorization:`Bearer ${env.GITHUB_CONTENTS_TOKEN}`,Accept:'application/vnd.github+json','Content-Type':'application/json','User-Agent':'MedLife-Articles-AI'},body:JSON.stringify({message:`feat: add article image ${path.split('/').pop()}`,content:b64(bytes),branch:'main'})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d?.message||`GitHub upload failed (${r.status})`);return d?.content?.download_url||`https://raw.githubusercontent.com/Medlifesy/medlife-website/main/${path}`;}
async function commons(q){const u='https://commons.wikimedia.org/w/api.php?action=query&generator=search&gsrnamespace=6&gsrlimit=5&gsrsearch='+encodeURIComponent(q)+'&prop=imageinfo&iiprop=url|mime|extmetadata&iiurlwidth=1400&format=json';const r=await fetch(u,{headers:{'User-Agent':'MedLife-Articles-AI/1.0'}});if(!r.ok)throw Error('تعذر البحث عن الصور.');const d=await r.json();return Object.values(d?.query?.pages||{}).map(x=>{const i=x.imageinfo?.[0]||{},m=i.extmetadata||{};return {title:x.title,download_url:i.thumburl||i.url,source_url:i.descriptionurl||i.url,mime:i.mime||'',width:i.thumbwidth||i.width||0,height:i.thumbheight||i.height||0,license:m.LicenseShortName?.value||m.UsageTerms?.value||'راجع المصدر'};}).filter(x=>/^image\/(jpeg|png|webp|gif)$/i.test(x.mime)&&x.download_url&&x.width>=700&&x.height>=400);}
async function autoImages(env,a){if(!env.AI)return {success:false,error:"Workers AI binding 'AI' is not configured on the deployed Worker."};const r=await env.AI.run('@cf/meta/llama-3.3-70b-instruct-fp8-fast',{messages:[{role:'system',content:'Return valid JSON only.'},{role:'user',content:aiPrompt('visual',a)}],max_tokens:3500,temperature:.1,response_format:{type:'json_object'}});const plan=parseAI(r),ss=(plan.image_suggestions||[]).slice(0,5),images=[];for(let i=0;i<ss.length;i++){const s=ss[i];try{const c=(await commons(s.query||s.purpose||a.title_ar||a.title))[0];if(!c)continue;const im=await fetch(c.download_url,{headers:{'User-Agent':'MedLife-Articles-AI/1.0'}});if(!im.ok)continue;const bytes=new Uint8Array(await im.arrayBuffer());if(bytes.length>6*1024*1024)continue;const ext=c.mime==='image/png'?'png':c.mime==='image/webp'?'webp':c.mime==='image/gif'?'gif':'jpg';const path=`article-images/${slug(a.title_ar||a.title)}/${String(i+1).padStart(2,'0')}-${slug(s.type)}.${ext}`;const image_url=await githubPut(env,path,bytes);images.push({...s,image_url,source_url:c.source_url,license:c.license,source_title:c.title});}catch(e){images.push({...s,error:e.message});}}return {success:true,images,editor_notes:plan.editor_notes||[]};}
export default{async fetch(req,env){if(req.method==='OPTIONS')return new Response(null,{headers:{...corsHeaders}});const u=new URL(req.url),p=u.pathname.split('/').filter(Boolean);try{
if(p[0]==='api'&&p[1]==='article-ai'){if(req.method!=='POST')return json({success:false,error:'Method not allowed'},405);if(!await sessionAuth(req,env))return json({success:false,error:'جلسة الإدارة غير صالحة أو منتهية.'},401);if(!env.AI)return json({success:false,error:"Workers AI binding 'AI' is not configured on the deployed Worker."},503);const b=await req.json().catch(()=>({})),action=String(b.action||b.mode||'full_edit'),a=b.article||{},o=a.content||a.content_ar||'';const r=await env.AI.run('@cf/meta/llama-3.3-70b-instruct-fp8-fast',{messages:[{role:'system',content:'You are MedLife senior medical editor. Return JSON only and preserve every scientific detail.'},{role:'user',content:aiPrompt(action,a)}],max_tokens:12000,temperature:.12,response_format:{type:'json_object'}});const out=normalize(action,parseAI(r),o);return json({success:true,action,article:out,engine:'Workers AI / Llama 3.3 70B Fast',preservation:action==='visual'||action==='seo'?'not_applicable':'validated'});}
if(p[0]==='api'&&p[1]==='article-images-auto'){if(req.method!=='POST')return json({success:false,error:'Method not allowed'},405);if(!await sessionAuth(req,env))return json({success:false,error:'جلسة الإدارة غير صالحة أو منتهية.'},401);const b=await req.json().catch(()=>({}));return json(await autoImages(env,b.article||{}));}
if(p[0]==='public'&&p[1]==='articles'){if(req.method!=='GET')return json({error:'Method not allowed'},405);if(p[2])return json(await env.DB.prepare("SELECT id,title_ar,title_en,slug,excerpt_ar,excerpt_en,content_ar,content_en,author_name,category,image_url,created_at,updated_at FROM articles WHERE slug=? AND status='published'").bind(p[2]).first());return json((await env.DB.prepare("SELECT id,title_ar,title_en,slug,excerpt_ar,excerpt_en,author_name,category,image_url,created_at,updated_at FROM articles WHERE status='published' AND slug IS NOT NULL ORDER BY created_at DESC").all()).results)}
if(p[0]==='articles'){if(!await sessionAuth(req,env))return json({error:'Unauthorized'},401);await ensureSlugColumn(env.DB);if(p.length===1&&req.method==='GET')return json((await env.DB.prepare('SELECT * FROM articles ORDER BY created_at DESC').all()).results);if(p.length===1&&req.method==='POST'){let b=await req.json(),articleSlug=await uniqueSlug(env.DB,b.title_ar||b.title_en||'article');let r=await env.DB.prepare('INSERT INTO articles (title_ar,title_en,excerpt_ar,excerpt_en,content_ar,content_en,author_name,author_email,category,image_url,status,slug) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)').bind(b.title_ar,b.title_en,b.excerpt_ar,b.excerpt_en,b.content_ar,b.content_en,b.author_name,b.author_email,b.category,b.image_url,b.status||'pending',articleSlug).run();return json(await env.DB.prepare('SELECT * FROM articles WHERE id=?').bind(r.meta.last_row_id).first(),201)}if(p[1]&&req.method==='DELETE'){await env.DB.prepare('DELETE FROM articles WHERE id=?').bind(p[1]).run();return json({success:true})}if(p[1]&&req.method==='PUT'){let b=await req.json();const current=await env.DB.prepare('SELECT slug FROM articles WHERE id=?').bind(p[1]).first();const articleSlug=current?.slug||await uniqueSlug(env.DB,b.title_ar||b.title_en||'article',p[1]);await env.DB.prepare('UPDATE articles SET title_ar=?,title_en=?,excerpt_ar=?,excerpt_en=?,content_ar=?,content_en=?,author_name=?,author_email=?,category=?,image_url=?,status=?,slug=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(b.title_ar,b.title_en,b.excerpt_ar,b.excerpt_en,b.content_ar,b.content_en,b.author_name,b.author_email,b.category,b.image_url,b.status,articleSlug,p[1]).run();return json(await env.DB.prepare('SELECT * FROM articles WHERE id=?').bind(p[1]).first())}if(p[1]&&p[2]==='status'&&req.method==='PATCH'){let b=await req.json(),current=await env.DB.prepare('SELECT * FROM articles WHERE id=?').bind(p[1]).first();if(!current)return json({error:'Article not found'},404);const articleSlug=current.slug||await uniqueSlug(env.DB,current.title_ar||current.title_en||'article',p[1]);await env.DB.prepare('UPDATE articles SET status=?,slug=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(b.status,articleSlug,p[1]).run();return json(await env.DB.prepare('SELECT * FROM articles WHERE id=?').bind(p[1]).first())}}
return json({error:'Not found'},404)}catch(e){console.error(e);return json({success:false,error:e?.message||'Internal error'},500)}}};