-- =========================================================
-- MEDLIFE DATABASE ARCHITECTURE
-- Cloudflare D1
--
-- Production bindings:
--   DB          -> medlife-articles -> articles
--   MEMBERS_DB  -> medlife-db       -> members
--
-- The databases are intentionally separate. Therefore articles
-- cannot use a SQLite foreign key to members. The application
-- validates author_member_id through MEMBERS_DB instead.
--
-- Run database/members-schema.sql against medlife-db.
-- Run database/articles-schema.sql against medlife-articles.
-- =========================================================
