const CONTENT_DS='6fdacc1d-7b08-4a25-8e85-4cbeff40bc25';
const PLASMA_DS='1c22fca6-8017-49d6-a679-b3eb885bbd8c';
const WRITER_DS='842398ff-cf96-4740-bdf0-5f9ab6f6caa0';
const ACCOUNTS_DS='8450cfc9-2ecf-4dcb-8fe3-80a0ecb81efb';
const NOTION_VERSION='2025-09-03',COOKIE='medlife_content_center_session',DAYS=7;
const CELL_ROLES=['مسؤول خلية','مشرف خلية'],ADMIN_ROLES=['إدارة المحتوى','مدير النظام'];
const enc=new TextEncoder();
function json(data,status=200,extra={}){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store, no-cache, must-revalidate, max-age=0',...extra}})}
function hex(bytes){return Array.from(new Uint8Array(bytes)).map(b=>b.toString(16).padStart(2,'0')).join('')}
async function sha(v){return hex(await crypto.subtle.digest('SHA-256',enc.encode(v)))}
function cookieValue(request){const raw=request.headers.get('Cookie')||'';for(const part of raw.split(';')){const p=part.trim();if(p.startsWith(COOKIE+'='))return decodeURIComponent(p.slice(COOKIE.length+1))}return null}
function setCookie(v,maxAge){return `${COOKIE}=${encodeURIComponent(v)}; Max-Age=${maxAge}; Path=/; HttpOnly; Secure; SameSite=Lax`}
function text(p){if(!p)return '';if(p.type==='title')return(p.title||[]).map(x=>x.plain_text||'').join('').trim();if(p.type==='rich_text')return(p.rich_text||[]).map(x=>x.plain_text||'').join('').trim();if(p.type==='select')return p.select?.name||'';if(p.type==='url')return p.url||'';if(p.type==='number')return p.number==null?'':String(p.number);if(p.type==='checkbox')return p.checkbox?'نعم':'';return ''}
function date(p){return p?.date?.start||''}
function title(v){return{title:[{text:{content:String(v)}}]}}
function rich(v){return{rich_text:v?[{text:{content:String(v)}}]:[]}}
function select(v){return{select:v?{name:String(v)}:null}}
function number(v){return{number:v===''||v==null?null:Number(v)}}
function checkbox(v){return{checkbox:Boolean(v)}}
function url(v){return{url:v?String(v):null}}
function dateProp(v){return{date:v?{start:String(v)}:null}}
function relation(pageUrl){return{relation:pageUrl?[{id:pageUrl}]:[]}}
async function notion(env,path,init={}){if(!env.NOTION_API_TOKEN)throw Error('NOTION_API_TOKEN is not configured');const r=await fetch('https://api.notion.com'+path,{...init,headers:{Authorization:`Bearer ${env.NOTION_API_TOKEN}`,'Notion-Version':NOTION_VERSION,'Content-Type':'application/json',...(init.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d?.message||d?.code||`Notion API returned ${r.status}`);return d}
async function queryAll(env,ds,filter){let out=[],cursor;for(let i=0;i<10;i++){const body={page_size:100,...(filter?{filter}:{}),...(cursor?{start_cursor:cursor}:{})};const d=await notion(env,`/v1/data_sources/${ds}/query`,{method:'POST',body:JSON.stringify(body)});out.push(...(d.results||[]));if(!d.has_more||!d.next_cursor)break;cursor=d.next_cursor}return out}
async function ensure(db){await db.prepare(`CREATE TABLE IF NOT EXISTS content_center_sessions(id INTEGER PRIMARY KEY AUTOINCREMENT,account_page_id TEXT NOT NULL,token_hash TEXT NOT NULL UNIQUE,expires_at TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run()}
async function identity(request,db,env){const token=cookieValue(request);if(!token)return null;const row=await db.prepare(`SELECT account_page_id FROM content_center_sessions WHERE token_hash=?1 AND datetime(expires_at)>datetime('now') LIMIT 1`).bind(await sha(token)).first();if(!row)return null;try{const p=await notion(env,`/v1/pages/${row.account_page_id}`);const x=p.properties||{};return{pageId:p.id,username:text(x['اسم المستخدم']),cell:text(x['الخلية']),status:text(x['الحالة']),role:text(x['الدور'])}}catch{return null}}
function dsFor(cell){return cell==='Plasma Cell'?PLASMA_DS:CONTENT_DS}
function map(page,cell){const p=page.properties||{};const plasma=cell==='Plasma Cell';return{id:page.id,url:page.url||'',title:text(p[plasma?'عنوان المنشور':'عنوان المحتوى']),cell:plasma?'Plasma Cell':text(p['الخلية']),unit:plasma?'خلية محتوى':text(p['القسم / الوحدة']),status:text(p['الحالة']),priority:text(p['الأولوية']),author:text(p[plasma?'الكاتب - اسم':'الكاتب']),cellManager:text(p[plasma?'مسؤول الخلية':'مسؤول الخلية']),created:plasma?(text(p['تاريخ إنشاء المحتوى'])||page.created_time||''):(date(p['تاريخ إنشاء المحتوى'])||page.created_time||''),formatPerson:text(p['منسق المحتوى']),formatDate:date(p['تاريخ التنسيق']),formatRating:text(p['تقييم التنسيق']),designPerson:text(p['المصمم - اسم']),designDate:date(p['تاريخ التصميم']),designRating:text(p['تقييم التصميم']),publishPerson:text(p['نشر بواسطة']),publishDate:date(p['تاريخ النشر']),publishedUrl:text(p['رابط المنشور']),designUrl:text(p['رابط التصميم']),published:p['تم النشر']?.checkbox===true}}
async function findWriter(env,name){if(!name)return null;const d=await notion(env,`/v1/data_sources/${WRITER_DS}/query`,{method:'POST',body:JSON.stringify({page_size:1,filter:{property:'اسم الكاتب',title:{equals:name}}})});return d.results?.[0]||null}
function allowed(a,action){if(!a)return false;if(ADMIN_ROLES.includes(a.role))return true;if(action==='create'||action==='publish')return CELL_ROLES.includes(a.role);if(action==='format')return a.role==='منسق';if(action==='design')return a.role==='مصمم';return false}
function visible(a,x){if(ADMIN_ROLES.includes(a.role))return true;if(a.role==='منسق')return x.unit==='التنسيق';if(a.role==='مصمم')return x.unit==='التصميم';return x.cell===a.cell}

export async function onRequest({request,env}){
 if(!env.DB)return json({success:false,error:"Database binding 'DB' is not configured."},500);const db=env.DB;await ensure(db);const u=new URL(request.url),action=u.searchParams.get('action')||'me';
 if(action==='login'&&request.method==='POST'){const b=await request.json().catch(()=>({}));const username=String(b.identifier||b.username||'').trim().toLowerCase(),password=String(b.password||'');if(!username||!password)return json({success:false,error:'يرجى إدخال اسم المستخدم وكلمة المرور.'},400);try{const d=await notion(env,`/v1/data_sources/${ACCOUNTS_DS}/query`,{method:'POST',body:JSON.stringify({page_size:1,filter:{property:'اسم المستخدم',title:{equals:username}}})});const p=d.results?.[0];if(!p)return json({success:false,error:'بيانات الدخول غير صحيحة.'},401);const x=p.properties||{},stored=text(x['كلمة المرور']);if(stored!==password)return json({success:false,error:'بيانات الدخول غير صحيحة.'},401);const a={pageId:p.id,username:text(x['اسم المستخدم']),cell:text(x['الخلية']),status:text(x['الحالة']),role:text(x['الدور'])};if(a.status!=='فعّال')return json({success:false,error:'الحساب غير مفعّل.'},401);const token=hex(crypto.getRandomValues(new Uint8Array(32)));await db.prepare('DELETE FROM content_center_sessions WHERE account_page_id=?1').bind(a.pageId).run();await db.prepare(`INSERT INTO content_center_sessions(account_page_id,token_hash,expires_at) VALUES(?1,?2,datetime('now','+7 days'))`).bind(a.pageId,await sha(token)).run();return json({success:true,identity:{type:ADMIN_ROLES.includes(a.role)?'admin':a.role==='منسق'||a.role==='مصمم'?'department':'cell',cell:a.cell,username:a.username,role:a.role}},200,{'Set-Cookie':setCookie(token,DAYS*86400)})}catch(e){return json({success:false,error:e.message||'تعذر تسجيل الدخول.'},502)}}
 if(action==='logout'&&request.method==='POST'){const t=cookieValue(request);if(t)await db.prepare('DELETE FROM content_center_sessions WHERE token_hash=?1').bind(await sha(t)).run();return json({success:true},200,{'Set-Cookie':setCookie('',0)})}
 const a=await identity(request,db,env);
 if(action==='me'&&request.method==='GET'){if(a)return json({success:true,authenticated:true,identity:{type:ADMIN_ROLES.includes(a.role)?'admin':a.role==='منسق'||a.role==='مصمم'?'department':'cell',cell:a.cell,username:a.username,role:a.role}});return json({success:false,authenticated:false},401)}
 if(action==='list'&&request.method==='GET'){if(!a)return json({success:false,error:'Unauthorized'},401);try{let pages=[];if(a.cell==='Plasma Cell'){pages=await queryAll(env,PLASMA_DS)}else if(ADMIN_ROLES.includes(a.role)){const old=await queryAll(env,CONTENT_DS);const plasma=await queryAll(env,PLASMA_DS);pages=[...old,...plasma]}else{pages=await queryAll(env,CONTENT_DS,{and:[{property:'الخلية',select:{equals:a.cell}}]})}let items=pages.map(p=>map(p,pages===pages?((p.properties||{})['عنوان المنشور']?'Plasma Cell':a.cell):a.cell)).filter(x=>visible(a,x));const s=u.searchParams.get('status');if(s)items=items.filter(x=>x.status===s);return json({success:true,items})}catch(e){return json({success:false,error:e.message||'تعذر تحميل المحتوى.'},502)}}
 if(action==='create'&&request.method==='POST'){if(!a||a.status!=='فعّال'||!allowed(a,'create'))return json({success:false,error:'ليس لديك صلاحية إضافة محتوى.'},403);if(a.cell!=='Plasma Cell')return json({success:false,error:'الإضافة المعزولة متاحة حالياً لخلية Plasma فقط.'},409);const b=await request.json().catch(()=>({})),postTitle=String(b.title||'').trim(),writerName=String(b.author||'').trim(),body=String(b.body||''),priority=String(b.priority||'متوسطة');if(!postTitle)return json({success:false,error:'عنوان المنشور مطلوب.'},400);if(!writerName)return json({success:false,error:'اختر كاتب المحتوى.'},400);try{const writer=await findWriter(env,writerName);if(!writer)return json({success:false,error:'كاتب المحتوى غير موجود في قائمة Plasma.'},400);const props={'عنوان المنشور':title(postTitle),'الكاتب':{relation:[{id:writer.id} ]},'الكاتب - اسم':rich(writerName),'مسؤول الخلية':rich(a.username),'الحالة':select('قيد الكتابة'),'الأولوية':select(priority),'نص المحتوى':rich(body),'تاريخ التكليف':dateProp(new Date().toISOString().slice(0,10))};const page=await notion(env,'/v1/pages',{method:'POST',body:JSON.stringify({parent:{data_source_id:PLASMA_DS},properties:props})});return json({success:true,item:map(page,'Plasma Cell')})}catch(e){console.error('content-center create',e);return json({success:false,error:e.message||'تعذر إنشاء المنشور.'},502)}}
 if(['format','design','publish'].includes(action)&&request.method==='POST'){if(!a||!allowed(a,action))return json({success:false,error:'ليس لديك صلاحية تنفيذ هذه العملية.'},403);const b=await request.json().catch(()=>({})),id=String(b.page_id||'').trim();if(!id)return json({success:false,error:'المحتوى غير محدد.'},400);try{const page=await notion(env,`/v1/pages/${id}`),isPlasma=Boolean(page.properties?.['عنوان المنشور']),ds=isPlasma?PLASMA_DS:CONTENT_DS;const x=map(page,isPlasma?'Plasma Cell':a.cell);if(!visible(a,x))return json({success:false,error:'غير مصرح لك بهذا المحتوى.'},403);const today=String(b.date||new Date().toISOString().slice(0,10));if(action==='format'){const rating=Number(b.rating);if(!Number.isFinite(rating)||rating<1||rating>10)return json({success:false,error:'أدخل تقييماً بين 1 و10.'},400);await notion(env,`/v1/pages/${id}`,{method:'PATCH',body:JSON.stringify({properties:{'منسق المحتوى':rich(String(b.person||a.username)),'تاريخ التنسيق':dateProp(today),'تقييم التنسيق':number(rating),'الحالة':select('قيد التصميم')}})});return json({success:true})}if(action==='design'){const rating=Number(b.rating);if(!Number.isFinite(rating)||rating<1||rating>10)return json({success:false,error:'أدخل تقييماً بين 1 و10.'},400);const props={'المصمم - اسم':rich(String(b.person||a.username)),'تاريخ التصميم':dateProp(today),'تقييم التصميم':number(rating),'الحالة':select('جاهز للنشر')};if(b.design_url)props['رابط التصميم']=url(b.design_url);await notion(env,`/v1/pages/${id}`,{method:'PATCH',body:JSON.stringify({properties:props})});return json({success:true})}if(action==='publish'){const props={'الحالة':select('منشور'),'تم النشر':checkbox(true),'تاريخ النشر':dateProp(today),'نشر بواسطة':rich(a.username),'منصة النشر':{multi_select:[{name:String(b.platform||'Facebook')}]},'ملاحظات النشر':rich(String(b.notes||''))};if(b.url)props['رابط المنشور']=url(b.url);await notion(env,`/v1/pages/${id}`,{method:'PATCH',body:JSON.stringify({properties:props})});return json({success:true})}}catch(e){return json({success:false,error:e.message||'تعذر تحديث المحتوى.'},502)}}
 return json({success:false,error:'Unsupported action.'},404)
}