import { authenticateArticleAdmin } from './article-admin-session.js';

const CONTENT_DS = '6fdacc1d-7b08-4a25-8e85-4cbeff40bc25';
const ACCOUNTS_DS = '8450cfc9-2ecf-4dcb-8fe3-80a0ecb81efb';
const NOTION_VERSION = '2025-09-03';
const COOKIE = 'medlife_content_center_session';
const DAYS = 7;
const enc = new TextEncoder();

function json(data, status=200, extra={}) {
  return new Response(JSON.stringify(data), {status, headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store, no-cache, must-revalidate, max-age=0',...extra}});
}
function hex(bytes){return Array.from(new Uint8Array(bytes)).map(b=>b.toString(16).padStart(2,'0')).join('');}
async function sha(v){return hex(await crypto.subtle.digest('SHA-256',enc.encode(v)));}
function cookieValue(request,name){const raw=request.headers.get('Cookie')||'';for(const part of raw.split(';')){const p=part.trim();if(p.startsWith(name+'='))return decodeURIComponent(p.slice(name.length+1));}return null;}
function setCookie(name,value,maxAge){return `${name}=${encodeURIComponent(value)}; Max-Age=${maxAge}; Path=/; HttpOnly; Secure; SameSite=Lax`;}
function prop(p){if(!p)return '';if(p.type==='title')return (p.title||[]).map(x=>x.plain_text||'').join('').trim();if(p.type==='rich_text')return (p.rich_text||[]).map(x=>x.plain_text||'').join('').trim();if(p.type==='select')return p.select?.name||'';if(p.type==='url')return p.url||'';if(p.type==='number')return p.number==null?'':String(p.number);return '';}
function date(p){return p?.date?.start||'';}
async function notion(env,path,init={}){if(!env.NOTION_API_TOKEN)throw new Error('NOTION_API_TOKEN is not configured');const r=await fetch(`https://api.notion.com${path}`,{...init,headers:{Authorization:`Bearer ${env.NOTION_API_TOKEN}`,'Notion-Version':NOTION_VERSION,'Content-Type':'application/json',...(init.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.message||d?.code||`Notion API returned ${r.status}`);return d;}
async function query(env,ds,body={}){return notion(env,`/v1/data_sources/${ds}/query`,{method:'POST',body:JSON.stringify({page_size:100,...body})});}
async function account(env,username){const d=await query(env,ACCOUNTS_DS,{filter:{property:'اسم المستخدم',title:{equals:username}},page_size:1});const page=d.results?.[0];if(!page)return null;const p=page.properties||{};return{pageId:page.id,username:prop(p['اسم المستخدم']),password:prop(p['كلمة المرور']),cell:prop(p['الخلية']),status:prop(p['الحالة']),role:prop(p['الدور'])};}
async function activeSession(request,db,env){const token=cookieValue(request,COOKIE);if(!token)return null;const row=await db.prepare(`SELECT account_page_id FROM content_center_sessions WHERE token_hash=?1 AND datetime(expires_at)>datetime('now') LIMIT 1`).bind(await sha(token)).first();if(!row)return null;return notion(env,`/v1/pages/${row.account_page_id}`).then(page=>{const p=page.properties||{};return{pageId:page.id,username:prop(p['اسم المستخدم']),cell:prop(p['الخلية']),status:prop(p['الحالة']),role:prop(p['الدور'])};}).catch(()=>null);}
async function ensure(db){await db.prepare(`CREATE TABLE IF NOT EXISTS content_center_sessions (id INTEGER PRIMARY KEY AUTOINCREMENT,account_page_id TEXT NOT NULL,token_hash TEXT NOT NULL UNIQUE,expires_at TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();}
function mapContent(page){const p=page.properties||{};return{id:page.id,url:page.url||null,title:prop(p['عنوان المحتوى']),cell:prop(p['الخلية']),unit:prop(p['القسم / الوحدة']),status:prop(p['الحالة']),priority:prop(p['الأولوية']),author:prop(p['الكاتب']),cellManager:prop(p['مسؤول الخلية']),due:date(p['تاريخ التسليم الفعلي']),publish:date(p['تاريخ النشر']),updated:page.last_edited_time||'',published:p['تم النشر']?.checkbox===true,designUrl:prop(p['رابط التصميم'])||null,publishedUrl:prop(p['رابط المنشور'])||null};}
async function admin(request,db){return Boolean(await authenticateArticleAdmin(request,db));}

export async function onRequest({request,env}){
  if(!env.DB)return json({success:false,error:"Database binding 'DB' is not configured."},500);
  const db=env.DB;await ensure(db);const url=new URL(request.url);const action=url.searchParams.get('action')||'me';
  if(action==='login'&&request.method==='POST'){
    const b=await request.json().catch(()=>({}));const username=String(b.identifier||b.username||'').trim().toLowerCase();const password=String(b.password||'');if(!username||!password)return json({success:false,error:'يرجى إدخال اسم المستخدم وكلمة المرور.'},400);
    try{const a=await account(env,username);if(!a||a.status!=='فعّال'||!['مسؤول خلية','إدارة المحتوى'].includes(a.role))return json({success:false,error:'بيانات الدخول غير صحيحة أو الحساب غير مفعّل.'},401);const ok=await (async()=>{const parts=a.password.split('$');if(parts.length===5&&parts[0]==='pbkdf2'&&parts[1]==='sha256'){const it=Number(parts[2]);if(Number.isInteger(it)&&it>=10000&&it<=1000000){try{const salt=Uint8Array.from((parts[3].match(/../g)||[]).map(x=>parseInt(x,16)));const expected=Uint8Array.from((parts[4].match(/../g)||[]).map(x=>parseInt(x,16)));const key=await crypto.subtle.importKey('raw',enc.encode(password),{name:'PBKDF2'},false,['deriveBits']);const bits=new Uint8Array(await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:it,hash:'SHA-256'},key,256));if(bits.length===expected.length&&bits.every((v,i)=>v===expected[i]))return true;}catch{}}}return a.password===password;})();if(!ok)return json({success:false,error:'بيانات الدخول غير صحيحة.'},401);const token=hex(crypto.getRandomValues(new Uint8Array(32)));await db.prepare(`DELETE FROM content_center_sessions WHERE account_page_id=?1`).bind(a.pageId).run();await db.prepare(`INSERT INTO content_center_sessions(account_page_id,token_hash,expires_at) VALUES(?1,?2,datetime('now','+7 days'))`).bind(a.pageId,await sha(token)).run();return json({success:true,identity:{type:'cell',cell:a.cell,username:a.username,role:a.role}},200,{'Set-Cookie':setCookie(COOKIE,token,DAYS*86400)});}catch(e){console.error('content-center login',e);return json({success:false,error:e instanceof Error?e.message:'تعذر تسجيل الدخول.'},502);}
  }
  if(action==='logout'&&request.method==='POST'){const t=cookieValue(request,COOKIE);if(t)await db.prepare('DELETE FROM content_center_sessions WHERE token_hash=?1').bind(await sha(t)).run();return json({success:true},200,{'Set-Cookie':setCookie(COOKIE,'',0)});}
  if(action==='me'&&request.method==='GET'){const a=await activeSession(request,db,env);if(a&&a.status==='فعّال')return json({success:true,authenticated:true,identity:{type:'cell',cell:a.cell,username:a.username,role:a.role}});const ad=await admin(request,db);if(ad)return json({success:true,authenticated:true,identity:{type:'admin',label:'الإدارة'}});return json({success:true,authenticated:false},401);}
  if(action==='accounts'&&request.method==='GET'){if(!(await admin(request,db)))return json({success:false,error:'Unauthorized'},401);try{const d=await query(env,ACCOUNTS_DS);return json({success:true,accounts:(d.results||[]).map(page=>{const p=page.properties||{};return{pageId:page.id,username:prop(p['اسم المستخدم']),cell:prop(p['الخلية']),status:prop(p['الحالة']),role:prop(p['الدور']),lastLogin:date(p['آخر دخول']),notes:prop(p['ملاحظات'])};})});}catch(e){return json({success:false,error:e instanceof Error?e.message:'تعذر تحميل الحسابات.'},502);}}
  if(action==='account-create'&&request.method==='POST'){if(!(await admin(request,db)))return json({success:false,error:'Unauthorized'},401);const b=await request.json().catch(()=>({}));const username=String(b.username||'').trim().toLowerCase();const password=String(b.password||'');const cell=String(b.cell_name||'').trim();const role=String(b.role||'مسؤول خلية').trim();const notes=String(b.notes||'').trim();if(!username||!cell||password.length<8)return json({success:false,error:'أدخل اسم المستخدم والخلية وكلمة مرور من 8 محارف على الأقل.'},400);try{const page=await notion(env,'/v1/pages',{method:'POST',body:JSON.stringify({parent:{data_source_id:ACCOUNTS_DS},properties:{'اسم المستخدم':{title:[{text:{content:username}}]},'كلمة المرور':{rich_text:[{text:{content:password}}]},'الخلية':{select:{name:cell}},'الحالة':{select:{name:'فعّال'}},'الدور':{select:{name:role}},'ملاحظات':{rich_text:notes?[{text:{content:notes}}]:[]}}})});return json({success:true,account:{pageId:page.id,username,cell,role}});}catch(e){return json({success:false,error:e instanceof Error?e.message:'تعذر إنشاء الحساب.'},409);}}
  if(action==='account-toggle'&&request.method==='POST'){if(!(await admin(request,db)))return json({success:false,error:'Unauthorized'},401);const b=await request.json().catch(()=>({}));const pageId=String(b.page_id||'').trim();if(!pageId)return json({success:false,error:'Invalid account.'},400);try{await notion(env,`/v1/pages/${pageId}`,{method:'PATCH',body:JSON.stringify({properties:{'الحالة':{select:{name:b.active===true?'فعّال':'موقوف'}}}})});return json({success:true});}catch(e){return json({success:false,error:e instanceof Error?e.message:'تعذر تحديث الحساب.'},502);}}
  if(action!=='list'||request.method!=='GET')return json({success:false,error:'Unsupported action or method.'},405);
  const ad=await admin(request,db);let scope='';let identity=null;if(!ad){identity=await activeSession(request,db,env);if(!identity||identity.status!=='فعّال')return json({success:false,authenticated:false,error:'يجب تسجيل الدخول إلى مركز المحتوى.'},401);scope=identity.cell;}
  const requested=url.searchParams.get('cell')?.trim()||'';const status=url.searchParams.get('status')?.trim()||'';const filters=[];if(scope)filters.push({property:'الخلية',select:{equals:scope}});else if(requested)filters.push({property:'الخلية',select:{equals:requested}});if(status)filters.push({property:'الحالة',select:{equals:status}});const body={};if(filters.length===1)body.filter=filters[0];if(filters.length>1)body.filter={and:filters};body.sorts=[{timestamp:'last_edited_time',direction:'descending'}];try{const d=await query(env,CONTENT_DS,body);return json({success:true,identity:ad?{type:'admin',label:'الإدارة'}:{type:'cell',cell:scope,username:identity?.username||null,role:identity?.role||'مسؤول خلية'},items:(d.results||[]).map(mapContent),hasMore:Boolean(d.has_more),nextCursor:d.next_cursor||null});}catch(e){console.error('content-center list',e);return json({success:false,error:e instanceof Error?e.message:'تعذر تحميل محتوى Notion.'},502);}
}
