import { authenticateArticleAdmin } from './article-admin-session.js';

const CONTENT_DS = '6fdacc1d-7b08-4a25-8e85-4cbeff40bc25';
const ACCOUNTS_DS = '8450cfc9-2ecf-4dcb-8fe3-80a0ecb81efb';
const NOTION_VERSION = '2025-09-03';
const COOKIE = 'medlife_content_center_session';
const DAYS = 7;
const CELL_ROLES = ['مسؤول خلية','مشرف خلية'];
const ADMIN_ROLES = ['إدارة المحتوى','مدير النظام'];
const enc = new TextEncoder();

function json(data,status=200,extra={}){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store, no-cache, must-revalidate, max-age=0',...extra}})}
function hex(bytes){return Array.from(new Uint8Array(bytes)).map(b=>b.toString(16).padStart(2,'0')).join('')}
async function sha(v){return hex(await crypto.subtle.digest('SHA-256',enc.encode(v)))}
function cookieValue(request,name){const raw=request.headers.get('Cookie')||'';for(const part of raw.split(';')){const p=part.trim();if(p.startsWith(name+'='))return decodeURIComponent(p.slice(name.length+1))}return null}
function setCookie(name,value,maxAge){return `${name}=${encodeURIComponent(value)}; Max-Age=${maxAge}; Path=/; HttpOnly; Secure; SameSite=Lax`}
function prop(p){if(!p)return '';if(p.type==='title')return (p.title||[]).map(x=>x.plain_text||'').join('').trim();if(p.type==='rich_text')return (p.rich_text||[]).map(x=>x.plain_text||'').join('').trim();if(p.type==='select')return p.select?.name||'';if(p.type==='url')return p.url||'';if(p.type==='number')return p.number==null?'':String(p.number);if(p.type==='checkbox')return p.checkbox===true?'نعم':'';return ''}
function date(p){return p?.date?.start||''}
async function notion(env,path,init={}){if(!env.NOTION_API_TOKEN)throw new Error('NOTION_API_TOKEN is not configured');const r=await fetch(`https://api.notion.com${path}`,{...init,headers:{Authorization:`Bearer ${env.NOTION_API_TOKEN}`,'Notion-Version':NOTION_VERSION,'Content-Type':'application/json',...(init.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.message||d?.code||`Notion API returned ${r.status}`);return d}
async function query(env,ds,body={}){return notion(env,`/v1/data_sources/${ds}/query`,{method:'POST',body:JSON.stringify({page_size:100,...body})})}
async function queryAll(env,ds,body={}){let results=[],cursor=null;for(let i=0;i<10;i++){const d=await query(env,ds,{...body,...(cursor?{start_cursor:cursor}:{})});results.push(...(d.results||[]));if(!d.has_more||!d.next_cursor)break;cursor=d.next_cursor}return results}
async function account(env,username){const d=await query(env,ACCOUNTS_DS,{filter:{property:'اسم المستخدم',title:{equals:username}},page_size:1});const page=d.results?.[0];if(!page)return null;const p=page.properties||{};return{pageId:page.id,username:prop(p['اسم المستخدم']),password:prop(p['كلمة المرور']),cell:prop(p['الخلية']),status:prop(p['الحالة']),role:prop(p['الدور'])}}
async function activeSession(request,db,env){const token=cookieValue(request,COOKIE);if(!token)return null;const row=await db.prepare(`SELECT account_page_id FROM content_center_sessions WHERE token_hash=?1 AND datetime(expires_at)>datetime('now') LIMIT 1`).bind(await sha(token)).first();if(!row)return null;return notion(env,`/v1/pages/${row.account_page_id}`).then(page=>{const p=page.properties||{};return{pageId:page.id,username:prop(p['اسم المستخدم']),cell:prop(p['الخلية']),status:prop(p['الحالة']),role:prop(p['الدور'])}}).catch(()=>null)}
async function ensure(db){await db.prepare(`CREATE TABLE IF NOT EXISTS content_center_sessions (id INTEGER PRIMARY KEY AUTOINCREMENT,account_page_id TEXT NOT NULL,token_hash TEXT NOT NULL UNIQUE,expires_at TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run()}
function mapContent(page){const p=page.properties||{};return{id:page.id,url:page.url||null,title:prop(p['عنوان المحتوى']),cell:prop(p['الخلية']),unit:prop(p['القسم / الوحدة']),status:prop(p['الحالة']),priority:prop(p['الأولوية']),author:prop(p['الكاتب']),cellManager:prop(p['مسؤول الخلية']),due:date(p['تاريخ التسليم الفعلي']),publish:date(p['تاريخ النشر']),created:date(p['تاريخ إنشاء المحتوى'])||page.created_time||'',updated:page.last_edited_time||'',published:p['تم النشر']?.checkbox===true,designUrl:prop(p['رابط التصميم'])||null,publishedUrl:prop(p['رابط المنشور'])||null,formatPerson:prop(p['منسق المحتوى']),formatDate:date(p['تاريخ التنسيق']),formatRating:prop(p['تقييم التنسيق']),designPerson:prop(p['المصمم - اسم']),designDate:date(p['تاريخ التصميم']),designRating:prop(p['تقييم التصميم']),publishPerson:prop(p['نشر بواسطة']),publishNotes:prop(p['ملاحظات النشر']),platform:prop(p['منصة النشر']),contentRating:prop(p['تقييم المحتوى'])}}
async function admin(request,db){return Boolean(await authenticateArticleAdmin(request,db))}
async function hashPassword(password){const iterations=120000;const salt=crypto.getRandomValues(new Uint8Array(16));const key=await crypto.subtle.importKey('raw',enc.encode(password),{name:'PBKDF2'},false,['deriveBits']);const bits=new Uint8Array(await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations,hash:'SHA-256'},key,256));return `pbkdf2$sha256$${iterations}$${hex(salt)}$${hex(bits)}`}
async function verifyPassword(password,stored){const parts=String(stored||'').split('$');if(parts.length===5&&parts[0]==='pbkdf2'&&parts[1]==='sha256'){const it=Number(parts[2]);if(Number.isInteger(it)&&it>=10000&&it<=1000000){try{const salt=Uint8Array.from((parts[3].match(/../g)||[]).map(x=>parseInt(x,16)));const expected=Uint8Array.from((parts[4].match(/../g)||[]).map(x=>parseInt(x,16)));const key=await crypto.subtle.importKey('raw',enc.encode(password),{name:'PBKDF2'},false,['deriveBits']);const bits=new Uint8Array(await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:it,hash:'SHA-256'},key,256));return bits.length===expected.length&&bits.every((v,i)=>v===expected[i])}catch{return false}}}return stored===password}
function textProp(v){return{rich_text:v?[{text:{content:String(v)}}]:[]}}
function titleProp(v){return{title:[{text:{content:String(v)}}]}}
function selectProp(v){return{select:v?{name:String(v)}:null}}
function dateProp(v){return{date:v?{start:String(v)}:null}}
function numberProp(v){return{number:v===''||v==null?null:Number(v)}}
function checkboxProp(v){return{checkbox:Boolean(v)}}
function urlProp(v){return{url:v?String(v):null}}
function allowed(identity,action){const role=identity?.role||'';if(ADMIN_ROLES.includes(role))return true;if(action==='create')return CELL_ROLES.includes(role);if(action==='format')return role==='منسق';if(action==='design')return role==='مصمم';if(action==='publish')return CELL_ROLES.includes(role);return false}
function canSee(identity,item){const role=identity?.role||'';if(ADMIN_ROLES.includes(role))return true;if(role==='منسق')return item.unit==='التنسيق';if(role==='مصمم')return item.unit==='التصميم';return Boolean(identity?.cell)&&item.cell===identity.cell}
function nextStage(item){if(item.formatPerson&&item.formatDate&&item.formatRating&&item.designPerson&&item.designDate&&item.designRating)return 'جاهز للنشر';if(item.formatPerson&&item.formatDate&&item.formatRating)return 'قيد التصميم';return 'قيد التنسيق'}
async function patchContent(env,pageId,properties){return notion(env,`/v1/pages/${pageId}`,{method:'PATCH',body:JSON.stringify({properties})})}

export async function onRequest({request,env}){
if(!env.DB)return json({success:false,error:"Database binding 'DB' is not configured."},500);const db=env.DB;await ensure(db);const url=new URL(request.url);const action=url.searchParams.get('action')||'me';
if(action==='login'&&request.method==='POST'){const b=await request.json().catch(()=>({}));const username=String(b.identifier||b.username||'').trim().toLowerCase();const password=String(b.password||'');if(!username||!password)return json({success:false,error:'يرجى إدخال اسم المستخدم وكلمة المرور.'},400);try{const a=await account(env,username);if(!a||a.status!=='فعّال'||![...CELL_ROLES,...ADMIN_ROLES,'منسق','مصمم'].includes(a.role))return json({success:false,error:'بيانات الدخول غير صحيحة أو الحساب غير مفعّل.'},401);if(!(await verifyPassword(password,a.password)))return json({success:false,error:'بيانات الدخول غير صحيحة.'},401);const token=hex(crypto.getRandomValues(new Uint8Array(32)));await db.prepare(`DELETE FROM content_center_sessions WHERE account_page_id=?1`).bind(a.pageId).run();await db.prepare(`INSERT INTO content_center_sessions(account_page_id,token_hash,expires_at) VALUES(?1,?2,datetime('now','+7 days'))`).bind(a.pageId,await sha(token)).run();return json({success:true,identity:{type:ADMIN_ROLES.includes(a.role)?'admin':a.role==='منسق'||a.role==='مصمم'?'department':'cell',cell:a.cell||'',username:a.username,role:a.role}},200,{'Set-Cookie':setCookie(COOKIE,token,DAYS*86400)})}catch(e){console.error('content-center login',e);return json({success:false,error:e instanceof Error?e.message:'تعذر تسجيل الدخول.'},502)}}
if(action==='logout'&&request.method==='POST'){const t=cookieValue(request,COOKIE);if(t)await db.prepare('DELETE FROM content_center_sessions WHERE token_hash=?1').bind(await sha(t)).run();return json({success:true},200,{'Set-Cookie':setCookie(COOKIE,'',0)})}
if(action==='me'&&request.method==='GET'){const a=await activeSession(request,db,env);if(a&&a.status==='فعّال')return json({success:true,authenticated:true,identity:{type:ADMIN_ROLES.includes(a.role)?'admin':a.role==='منسق'||a.role==='مصمم'?'department':'cell',cell:a.cell||'',username:a.username,role:a.role}});const ad=await admin(request,db);if(ad)return json({success:true,authenticated:true,identity:{type:'admin',label:'الإدارة',role:'إدارة المحتوى'}});return json({success:true,authenticated:false},401)}
if(action==='accounts'&&request.method==='GET'){if(!(await admin(request,db)))return json({success:false,error:'Unauthorized'},401);try{const pages=await queryAll(env,ACCOUNTS_DS);return json({success:true,accounts:pages.map(page=>{const p=page.properties||{};return{pageId:page.id,username:prop(p['اسم المستخدم']),cell:prop(p['الخلية']),status:prop(p['الحالة']),role:prop(p['الدور']),lastLogin:date(p['آخر دخول']),notes:prop(p['ملاحظات'])}})})}catch(e){return json({success:false,error:e instanceof Error?e.message:'تعذر تحميل الحسابات.'},502)}}
if(action==='account-create'&&request.method==='POST'){if(!(await admin(request,db)))return json({success:false,error:'Unauthorized'},401);const b=await request.json().catch(()=>({}));const username=String(b.username||'').trim().toLowerCase();const password=String(b.password||'');const cell=String(b.cell_name||'').trim();const role=String(b.role||'مسؤول خلية').trim();const notes=String(b.notes||'').trim();if(!username||!cell||password.length<8)return json({success:false,error:'أدخل اسم المستخدم والخلية وكلمة مرور من 8 محارف على الأقل.'},400);if(![...CELL_ROLES,...ADMIN_ROLES,'منسق','مصمم'].includes(role))return json({success:false,error:'الدور غير مسموح.'},400);try{const existing=await account(env,username);if(existing)return json({success:false,error:'اسم المستخدم مستخدم مسبقاً.'},409);const hashed=await hashPassword(password);const page=await notion(env,'/v1/pages',{method:'POST',body:JSON.stringify({parent:{data_source_id:ACCOUNTS_DS},properties:{'اسم المستخدم':titleProp(username),'كلمة المرور':textProp(hashed),'الخلية':selectProp(cell),'الحالة':selectProp('فعّال'),'الدور':selectProp(role),'ملاحظات':textProp(notes)}})});return json({success:true,account:{pageId:page.id,username,cell,role}})}catch(e){return json({success:false,error:e instanceof Error?e.message:'تعذر إنشاء الحساب.'},409)}}
if(action==='account-toggle'&&request.method==='POST'){if(!(await admin(request,db)))return json({success:false,error:'Unauthorized'},401);const b=await request.json().catch(()=>({}));const pageId=String(b.page_id||'').trim();if(!pageId)return json({success:false,error:'Invalid account.'},400);try{await notion(env,`/v1/pages/${pageId}`,{method:'PATCH',body:JSON.stringify({properties:{'الحالة':selectProp(b.active===true?'فعّال':'موقوف')}})});return json({success:true})}catch(e){return json({success:false,error:e instanceof Error?e.message:'تعذر تحديث الحساب.'},502)}}
if(action==='create'&&request.method==='POST'){const identity=await activeSession(request,db,env);if(!identity||identity.status!=='فعّال'||!allowed(identity,'create'))return json({success:false,error:'ليس لديك صلاحية إضافة محتوى.'},403);const b=await request.json().catch(()=>({}));const title=String(b.title||'').trim();if(!title)return json({success:false,error:'عنوان المحتوى مطلوب.'},400);const today=new Date().toISOString().slice(0,10);try{const page=await notion(env,'/v1/pages',{method:'POST',body:JSON.stringify({parent:{data_source_id:CONTENT_DS},properties:{'عنوان المحتوى':titleProp(title),'الخلية':selectProp(identity.cell),'القسم / الوحدة':selectProp('خلية محتوى'),'الحالة':selectProp('قيد الكتابة'),'الأولوية':selectProp(String(b.priority||'متوسطة')),'الكاتب':textProp(String(b.author||identity.username)),'مسؤول الخلية':textProp(identity.username),'date:تاريخ إنشاء المحتوى:start':today,'date:تاريخ إنشاء المحتوى:is_datetime':0,'date:تاريخ التكليف:start':today,'date:تاريخ التكليف:is_datetime':0,'نص المحتوى':textProp(String(b.body||''))}})});return json({success:true,item:mapContent(page)})}catch(e){return json({success:false,error:e instanceof Error?e.message:'تعذر إنشاء المحتوى.'},502)}}
if(action==='format'&&request.method==='POST'){const identity=await activeSession(request,db,env);if(!identity||!allowed(identity,'format'))return json({success:false,error:'ليس لديك صلاحية تسجيل إنجاز التنسيق.'},403);const b=await request.json().catch(()=>({}));const pageId=String(b.page_id||'').trim();const person=String(b.person||identity.username).trim();const rating=Number(b.rating);const doneDate=String(b.date||new Date().toISOString().slice(0,10));if(!pageId||!person||!Number.isFinite(rating)||rating<1||rating>10)return json({success:false,error:'أدخل المنسق والتاريخ وتقييماً بين 1 و10.'},400);try{const current=await notion(env,`/v1/pages/${pageId}`);const item=mapContent(current);if(item.unit!=='التنسيق'&&item.unit!=='خلية محتوى')return json({success:false,error:'هذا المحتوى ليس في مسار التنسيق.'},409);const status=nextStage({...item,formatPerson:person,formatDate:doneDate,formatRating:String(rating)});await patchContent(env,pageId,{'منسق المحتوى':textProp(person),'تاريخ التنسيق':dateProp(doneDate),'تقييم التنسيق':numberProp(rating),'القسم / الوحدة':selectProp(status==='جاهز للنشر'||status==='قيد التصميم'?'التصميم':'التنسيق'),'الحالة':selectProp(status)});return json({success:true,status})}catch(e){return json({success:false,error:e instanceof Error?e.message:'تعذر تحديث التنسيق.'},502)}}
if(action==='design'&&request.method==='POST'){const identity=await activeSession(request,db,env);if(!identity||!allowed(identity,'design'))return json({success:false,error:'ليس لديك صلاحية تسجيل إنجاز التصميم.'},403);const b=await request.json().catch(()=>({}));const pageId=String(b.page_id||'').trim();const person=String(b.person||identity.username).trim();const rating=Number(b.rating);const doneDate=String(b.date||new Date().toISOString().slice(0,10));const designUrl=String(b.design_url||'').trim();if(!pageId||!person||!Number.isFinite(rating)||rating<1||rating>10)return json({success:false,error:'أدخل المصمم والتاريخ وتقييماً بين 1 و10.'},400);try{const current=await notion(env,`/v1/pages/${pageId}`);const item=mapContent(current);const status=nextStage({...item,designPerson:person,designDate:doneDate,designRating:String(rating)});const properties={'المصمم - اسم':textProp(person),'تاريخ التصميم':dateProp(doneDate),'تقييم التصميم':numberProp(rating),'الحالة':selectProp(status)};if(status==='جاهز للنشر')properties['القسم / الوحدة']=selectProp('خلية محتوى');if(designUrl)properties['رابط التصميم']=urlProp(designUrl);await patchContent(env,pageId,properties);return json({success:true,status})}catch(e){return json({success:false,error:e instanceof Error?e.message:'تعذر تحديث التصميم.'},502)}}
if(action==='publish'&&request.method==='POST'){const identity=await activeSession(request,db,env);if(!identity||!allowed(identity,'publish'))return json({success:false,error:'ليس لديك صلاحية تسجيل النشر.'},403);const b=await request.json().catch(()=>({}));const pageId=String(b.page_id||'').trim();const publishDate=String(b.date||new Date().toISOString().slice(0,10));const urlPublished=String(b.url||'').trim();const notes=String(b.notes||'').trim();const platform=String(b.platform||'Facebook').trim();if(!pageId)return json({success:false,error:'المحتوى غير محدد.'},400);try{const current=await notion(env,`/v1/pages/${pageId}`);const item=mapContent(current);if(item.cell!==identity.cell)return json({success:false,error:'لا يمكنك نشر محتوى خلية أخرى.'},403);if(item.status!=='جاهز للنشر'&&item.status!=='مجدول')return json({success:false,error:'لا يمكن تسجيل النشر قبل اكتمال التنسيق والتصميم.'},409);const properties={'الحالة':selectProp('منشور'),'تم النشر':checkboxProp(true),'تاريخ النشر':dateProp(publishDate),'نشر بواسطة':textProp(identity.username),'ملاحظات النشر':textProp(notes),'منصة النشر':{multi_select:[{name:platform}]}};if(urlPublished)properties['رابط المنشور']=urlProp(urlPublished);await patchContent(env,pageId,properties);return json({success:true,status:'منشور'})}catch(e){return json({success:false,error:e instanceof Error?e.message:'تعذر تسجيل النشر.'},502)}}
if(action==='update-content'&&request.method==='POST'){const identity=await activeSession(request,db,env);if(!identity)return json({success:false,error:'Unauthorized'},401);const b=await request.json().catch(()=>({}));const pageId=String(b.page_id||'').trim();if(!pageId)return json({success:false,error:'Invalid content.'},400);try{const current=await notion(env,`/v1/pages/${pageId}`);const item=mapContent(current);if(!canSee(identity,item))return json({success:false,error:'غير مصرح لك بهذا المحتوى.'},403);const properties={};if(b.title!=null)properties['عنوان المحتوى']=titleProp(String(b.title).trim());if(b.body!=null)properties['نص المحتوى']=textProp(String(b.body));if(b.priority!=null)properties['الأولوية']=selectProp(String(b.priority));if(b.author!=null&&CELL_ROLES.includes(identity.role))properties['الكاتب']=textProp(String(b.author));await patchContent(env,pageId,properties);return json({success:true})}catch(e){return json({success:false,error:e instanceof Error?e.message:'تعذر تحديث المحتوى.'},502)}}
if(action==='analytics'&&request.method==='GET'){const identity=await activeSession(request,db,env);if(!identity||!ADMIN_ROLES.includes(identity.role))return json({success:false,error:'Unauthorized'},401);try{const pages=await queryAll(env,CONTENT_DS);const items=pages.map(mapContent);const by=(arr,key)=>{const m={};for(const x of arr){const v=String(x[key]||'غير محدد').trim();if(!m[v])m[v]={name:v,count:0,ratingSum:0,ratingCount:0};m[v].count++;const r=Number(x[`${key}Rating`]);if(Number.isFinite(r)){m[v].ratingSum+=r;m[v].ratingCount++}}return Object.values(m).map(x=>({...x,avgRating:x.ratingCount?Math.round(x.ratingSum/x.ratingCount*10)/10:null})).sort((a,b)=>b.count-a.count)};const writers={};const formatters={};const designers={};for(const x of items){if(x.author)writers[x.author]=(writers[x.author]||0)+1;if(x.formatPerson)formatters[x.formatPerson]=(formatters[x.formatPerson]||0)+1;if(x.designPerson)designers[x.designPerson]=(designers[x.designPerson]||0)+1}return json({success:true,summary:{total:items.length,ready:items.filter(x=>x.status==='جاهز للنشر').length,published:items.filter(x=>x.status==='منشور').length,inProgress:items.filter(x=>!['فكرة','منشور','أرشيف'].includes(x.status)&&x.status!=='جاهز للنشر').length},cells:by(items,'cell'),writers:Object.entries(writers).map(([name,count])=>({name,count})).sort((a,b)=>b.count-a.count),formatters:Object.entries(formatters).map(([name,count])=>({name,count})).sort((a,b)=>b.count-a.count),designers:Object.entries(designers).map(([name,count])=>({name,count})).sort((a,b)=>b.count-a.count)})}catch(e){return json({success:false,error:e instanceof Error?e.message:'تعذر تحميل التقييم.'},502)}}
if(action==='list'&&request.method==='GET'){const ad=await admin(request,db);let identity=null;if(!ad){identity=await activeSession(request,db,env);if(!identity||identity.status!=='فعّال')return json({success:false,authenticated:false,error:'يجب تسجيل الدخول إلى مركز المحتوى.'},401)}else identity={role:'إدارة المحتوى',type:'admin'};const status=url.searchParams.get('status')?.trim()||'';const requested=url.searchParams.get('cell')?.trim()||'';const unit=url.searchParams.get('unit')?.trim()||'';const filters=[];if(identity.type!=='admin'){if(identity.role==='منسق')filters.push({property:'القسم / الوحدة',select:{equals:'التنسيق'}});else if(identity.role==='مصمم')filters.push({property:'القسم / الوحدة',select:{equals:'التصميم'}});else if(identity.cell)filters.push({property:'الخلية',select:{equals:identity.cell}})}else if(requested)filters.push({property:'الخلية',select:{equals:requested}});if(unit)filters.push({property:'القسم / الوحدة',select:{equals:unit}});if(status)filters.push({property:'الحالة',select:{equals:status}});const body={sorts:[{timestamp:'last_edited_time',direction:'descending'}]};if(filters.length===1)body.filter=filters[0];if(filters.length>1)body.filter={and:filters};try{const d=await query(env,CONTENT_DS,body);let items=(d.results||[]).map(mapContent);if(identity.type!=='admin')items=items.filter(x=>canSee(identity,x));return json({success:true,identity,items,hasMore:Boolean(d.has_more),nextCursor:d.next_cursor||null})}catch(e){return json({success:false,error:e instanceof Error?e.message:'تعذر تحميل محتوى Notion.'},502)}}
return json({success:false,error:'Unsupported action or method.'},405)}
