import { authenticateAdmin } from './_admin-auth.js';

async function ensureSchema(db) {
  await db.prepare(`CREATE TABLE IF NOT EXISTS media_posts (id INTEGER PRIMARY KEY AUTOINCREMENT, archive_code TEXT NOT NULL UNIQUE, slug TEXT NOT NULL UNIQUE, title TEXT NOT NULL, summary TEXT, content_html TEXT NOT NULL, category TEXT NOT NULL DEFAULT 'نشاط ميداني', location TEXT, activity_date TEXT, cover_image_url TEXT, status TEXT NOT NULL DEFAULT 'draft', author_name TEXT, created_by INTEGER, published_at TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();
  await db.prepare(`CREATE TABLE IF NOT EXISTS media_post_images (id INTEGER PRIMARY KEY AUTOINCREMENT, post_id INTEGER NOT NULL, image_url TEXT NOT NULL, caption TEXT, sort_order INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();
  await db.prepare('CREATE INDEX IF NOT EXISTS idx_media_posts_status_date ON media_posts(status, activity_date)').run();
  await db.prepare('CREATE INDEX IF NOT EXISTS idx_media_images_post ON media_post_images(post_id, sort_order)').run();
}
function clean(v,max=10000){return String(v??'').trim().slice(0,max)}
function idOf(v){const n=Number(v);return Number.isInteger(n)&&n>0?n:0}
function slugify(v){const s=clean(v,180).toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^\p{L}\p{N}]+/gu,'-').replace(/^-+|-+$/g,'');return s||`media-${Date.now()}`}
function code(id){return `MED-NEWS-${new Date().getUTCFullYear()}-${String(id).padStart(3,'0')}`}
function statusOk(v){return ['draft','published','archived'].includes(String(v))}
async function getPost(db,id){const p=await db.prepare('SELECT * FROM media_posts WHERE id=? LIMIT 1').bind(id).first();if(!p)return null;const r=await db.prepare('SELECT id,image_url,caption,sort_order FROM media_post_images WHERE post_id=? ORDER BY sort_order,id').bind(id).all();return {...p,images:r.results||[]}}
async function list(db,published=false){const q=published?"SELECT * FROM media_posts WHERE status='published' ORDER BY COALESCE(activity_date,created_at) DESC,id DESC":"SELECT * FROM media_posts ORDER BY COALESCE(activity_date,created_at) DESC,id DESC";const r=await db.prepare(q).all();const out=[];for(const p of (r.results||[])){const x=await db.prepare('SELECT id,image_url,caption,sort_order FROM media_post_images WHERE post_id=? ORDER BY sort_order,id').bind(p.id).all();out.push({...p,images:x.results||[]})}return out}
async function uniqueSlug(db,v,id=0){const base=slugify(v);let s=base,n=2;while(await db.prepare('SELECT id FROM media_posts WHERE slug=? AND id<>? LIMIT 1').bind(s,id).first())s=`${base}-${n++}`;return s}
function authDb(env){return env.TEAM_DB || env.MEMBERS_DB || env.DB}
async function admin(request,env){const adb=authDb(env);if(!adb)return null;const u=await authenticateAdmin(request,adb);if(!u)return null;const role=String(u.admin_role||'').toLowerCase();return ['system_admin','admin','editor'].includes(role)?u:null}
async function saveImages(db,postId,images){await db.prepare('DELETE FROM media_post_images WHERE post_id=?').bind(postId).run();for(let i=0;i<(Array.isArray(images)?images:[]).slice(0,30).length;i++){const x=images[i]||{},url=clean(x.image_url,2000);if(url)await db.prepare('INSERT INTO media_post_images(post_id,image_url,caption,sort_order) VALUES(?,?,?,?)').bind(postId,url,clean(x.caption,500),i).run()}}
export async function onRequest({request,env}){
  if(!env?.DB)return json({success:false,error:'Database binding DB is not configured.'},500);const db=env.DB;
  try{await ensureSchema(db);const u=new URL(request.url),id=idOf(u.searchParams.get('id')),slug=clean(u.searchParams.get('slug'),180);
    if(request.method==='GET'){if(id){const p=await getPost(db,id);return p&&p.status==='published'?json({success:true,post:p}):json({success:false,error:'المادة غير موجودة.'},404)}if(slug){const r=await db.prepare("SELECT id FROM media_posts WHERE slug=? AND status='published' LIMIT 1").bind(slug).first();return r?json({success:true,post:await getPost(db,r.id)}):json({success:false,error:'المادة غير موجودة.'},404)}return json({success:true,posts:await list(db,true)})}
    const user=await admin(request,env);if(!user)return json({success:false,error:'غير مصرح بالدخول إلى إدارة المركز الإعلامي.'},401);
    if(request.method==='POST'){const b=await request.json().catch(()=>({})),title=clean(b.title,500),content=clean(b.content_html,100000);if(!title||!content)return json({success:false,error:'العنوان ومحتوى التقرير مطلوبان.'},400);const st=statusOk(b.status)?String(b.status):'draft',sl=await uniqueSlug(db,b.slug||title),pub=st==='published'?new Date().toISOString():null;const r=await db.prepare(`INSERT INTO media_posts(archive_code,slug,title,summary,content_html,category,location,activity_date,cover_image_url,status,author_name,created_by,published_at) VALUES('PENDING',?,?,?,?,?,?,?,?,?,?,?,?)`).bind(sl,title,clean(b.summary,2000),content,clean(b.category,120)||'نشاط ميداني',clean(b.location,250),clean(b.activity_date,30),clean(b.cover_image_url,2000),st,clean(b.author_name,250)||user.full_name||user.username,user.member_id||null,pub).run();const newId=r.meta?.last_row_id;if(!newId)return json({success:false,error:'تعذر إنشاء المادة.'},500);await db.prepare('UPDATE media_posts SET archive_code=? WHERE id=?').bind(code(newId),newId).run();await saveImages(db,newId,b.images);return json({success:true,post:await getPost(db,newId)},201)}
    if(request.method==='PUT'){if(!id)return json({success:false,error:'معرّف المادة مطلوب.'},400);const old=await getPost(db,id);if(!old)return json({success:false,error:'المادة غير موجودة.'},404);const b=await request.json().catch(()=>({})),title=clean(b.title??old.title,500),st=statusOk(b.status)?String(b.status):old.status;if(!title)return json({success:false,error:'العنوان مطلوب.'},400);const sl=await uniqueSlug(db,b.slug||title,id),pub=st==='published'?(old.published_at||new Date().toISOString()):null;await db.prepare(`UPDATE media_posts SET slug=?,title=?,summary=?,content_html=?,category=?,location=?,activity_date=?,cover_image_url=?,status=?,author_name=?,published_at=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(sl,title,clean(b.summary??old.summary,2000),clean(b.content_html??old.content_html,100000),clean(b.category??old.category,120)||'نشاط ميداني',clean(b.location??old.location,250),clean(b.activity_date??old.activity_date,30),clean(b.cover_image_url??old.cover_image_url,2000),st,clean(b.author_name??old.author_name,250),pub,id).run();if(Array.isArray(b.images))await saveImages(db,id,b.images);return json({success:true,post:await getPost(db,id)})}
    if(request.method==='DELETE'){if(!id)return json({success:false,error:'معرّف المادة مطلوب.'},400);await db.prepare('DELETE FROM media_post_images WHERE post_id=?').bind(id).run();const r=await db.prepare('DELETE FROM media_posts WHERE id=?').bind(id).run();return r.meta?.changes?json({success:true}):json({success:false,error:'المادة غير موجودة.'},404)}
    return json({success:false,error:'Method not allowed.'},405)
  }catch(e){console.error('Media Center API error',e);return json({success:false,error:'تعذر تنفيذ العملية حالياً.',detail:String(e?.message||'')},500)}
}
function json(body,status=200){return new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json; charset=UTF-8','Cache-Control':'no-store'}})}
