/* MEDLIFE CURRENT MEMBER REGISTRATION API
   POST /api/members
   Current members submit full membership details and choose account credentials.
*/
import { ensureAuthTables, hashPassword, json } from './_auth.js';
export async function onRequest({request,env}){
 if(request.method==='OPTIONS')return json({success:true});
 if(request.method!=='POST')return json({success:false,error:'Method not allowed.'},405);
 if(!env.MEMBERS_DB)return json({success:false,error:"Database binding 'MEMBERS_DB' is not configured."},500);
 try{
  const b=await request.json(),c=(v,n=5000)=>String(v??'').trim().slice(0,n);
  const employment_status=c(b.employment_status,30), consultation_specialty=c(b.consultation_specialty,200);
  const d={full_name:c(b.full_name,150),mother_name:c(b.mother_name,150),national_id:c(b.national_id,40),date_of_birth:c(b.date_of_birth,20),email:c(b.email,200).toLowerCase(),phone:c(b.phone,40),gender:c(b.gender,20),academic_status:c(b.academic_status,40),education_level:c(b.education_level,150)||c(b.academic_status,40),university:c(b.university,250),faculty:c(b.faculty,200),study_year:c(b.study_year,80),graduation_year:c(b.graduation_year||b.doctor_graduation_year||b.resident_graduation_year||b.specialist_graduation_year,30),profession:c(b.profession||b.res_profession,150),workplace:c(b.workplace||b.res_workplace,250),resident_specialty:c(b.resident_specialty||b.doctor_specialty||b.specialty,150),residency_year:c(b.residency_year,80),residency_hospital:c(b.residency_hospital,250),address:c(b.address,500),governorate:c(b.governorate,100),medlife_role:c(b.medlife_role,80),cell:c(b.cell,80),field_location:c(b.field_location,100),join_date:c(b.join_date,30),volunteer_certificate:c(b.volunteer_certificate,10)||'no',password:String(b.password||'')};
  const roles=['volunteer','supervisor','general_supervisor','assistant_supervisor'],cells=['plasma_cell','neuron_cell','astrocyte_cell','leukocyte_cell','heart_cell','red_blood_cell','blog','design','video_editing','visual_media','instagram','telegram','administration','voice_over','coordination','university_media','field','consultations'],fields=['damascus','aleppo','tartous','latakia','homs','hasakah'];
  if(!d.full_name||!d.mother_name||!d.national_id||!d.date_of_birth||!d.phone||!d.gender||!d.academic_status||!d.governorate||!d.medlife_role||!d.cell||!d.join_date||!d.email||!d.password)return json({success:false,error:'يرجى تعبئة جميع الحقول الأساسية وإنشاء البريد وكلمة المرور.'},400);
  if(!/^\d{4}-\d{2}-\d{2}$/.test(d.date_of_birth))return json({success:false,error:'تاريخ الميلاد غير صالح.'},400);if(!['male','female'].includes(d.gender))return json({success:false,error:'الجنس المحدد غير صالح.'},400);if(!roles.includes(d.medlife_role))return json({success:false,error:'الصفة داخل MedLife غير صالحة.'},400);if(!cells.includes(d.cell))return json({success:false,error:'الخلية المحددة غير صالحة.'},400);if(!['yes','no'].includes(d.volunteer_certificate))return json({success:false,error:'قيمة شهادة التطوع غير صالحة.'},400);if(d.cell==='field'&&!fields.includes(d.field_location))return json({success:false,error:'يرجى اختيار المحافظة للعمل الميداني.'},400);if(d.cell!=='field'&&d.field_location)return json({success:false,error:'لا يمكن تحديد محافظة ميدانية إلا عند اختيار المجال الميداني.'},400);if(d.cell==='consultations'&&!consultation_specialty)return json({success:false,error:'يرجى تحديد الاختصاص الذي تقدم فيه الاستشارات.'},400);if(d.cell!=='consultations'&&consultation_specialty)return json({success:false,error:'اختصاص الاستشارات يُحدد فقط عند اختيار قسم الاستشارات.'},400);if(employment_status&& !['working','not_working'].includes(employment_status))return json({success:false,error:'حالة العمل غير صالحة.'},400);if(employment_status==='working'&&d.academic_status==='graduate'&&(!d.profession||!d.workplace))return json({success:false,error:'بما أنك تعمل حالياً، يرجى إدخال المهنة ومكان العمل.'},400);if(!/^\S+@\S+\.\S+$/.test(d.email))return json({success:false,error:'البريد الإلكتروني غير صالح.'},400);if(d.password.length<8)return json({success:false,error:'يجب أن تتكون كلمة المرور من 8 أحرف/أرقام على الأقل.'},400);
  await ensureAuthTables(env.MEMBERS_DB);
  const cols=await env.MEMBERS_DB.prepare('PRAGMA table_info(members)').all();const have=new Set((cols.results||[]).map(x=>x.name));for(const [name,type] of [['employment_status','TEXT'],['consultation_specialty','TEXT']])if(!have.has(name))await env.MEMBERS_DB.prepare(`ALTER TABLE members ADD COLUMN ${name} ${type}`).run();
  const duplicate=await env.MEMBERS_DB.prepare('SELECT id FROM members WHERE national_id=? OR lower(COALESCE(account_email,email,\'\'))=? LIMIT 1').bind(d.national_id,d.email).first();if(duplicate)return json({success:false,error:'يوجد سجل سابق مرتبط بالرقم الوطني أو البريد الإلكتروني.'},409);
  const passwordHash=await hashPassword(d.password),memberCode='ML-'+crypto.randomUUID().slice(0,8).toUpperCase();
  const r=await env.MEMBERS_DB.prepare(`INSERT INTO members(full_name,mother_name,national_id,date_of_birth,email,account_email,password_hash,account_status,member_code,phone,gender,education_level,study_year,university,resident_specialty,residency_year,residency_hospital,address,governorate,medlife_role,cell,field_location,join_date,volunteer_certificate,status,created_at,updated_at,academic_status,faculty,graduation_year,profession,workplace,employment_status,consultation_specialty) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'pending',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,?,?,?,?,?,?,?)`).bind(d.full_name,d.mother_name,d.national_id,d.date_of_birth,d.email,d.email,passwordHash,'pending',memberCode,d.phone,d.gender,d.education_level,d.study_year,d.university,d.resident_specialty,d.residency_year,d.residency_hospital,d.address,d.governorate,d.medlife_role,d.cell,d.cell==='field'?d.field_location:null,d.join_date,d.volunteer_certificate,d.academic_status,d.faculty,d.graduation_year,d.profession,d.workplace,employment_status||null,consultation_specialty||null).run();
  return json({success:true,message:'تم استلام بيانات العضوية وإنشاء بيانات الحساب بنجاح. الحساب بانتظار موافقة الإدارة.',id:r.meta?.last_row_id??null,member_code:memberCode,status:'pending'},201);
 }catch(e){console.error(e);return json({success:false,error:'تعذر إرسال بيانات العضوية حالياً.'},500)}
}
