/* MEDLIFE CURRENT MEMBER REGISTRATION API
   POST /api/members
   Current members submit full membership details. */
export async function onRequest({request,env}){
 if(request.method==='OPTIONS')return out({success:true});
 if(request.method!=='POST')return out({success:false,error:'Method not allowed.'},405);
 if(!env.MEMBERS_DB)return out({success:false,error:"Database binding 'MEMBERS_DB' is not configured."},500);
 try{
  const b=await request.json(),c=(v,n=5000)=>String(v??'').trim().slice(0,n);
  const d={full_name:c(b.full_name,150),mother_name:c(b.mother_name,150),national_id:c(b.national_id,40),email:c(b.email,200).toLowerCase(),phone:c(b.phone,40),gender:c(b.gender,20),academic_status:c(b.academic_status,40),education_level:c(b.education_level,150)||c(b.academic_status,40),university:c(b.university,250),faculty:c(b.faculty,200),study_year:c(b.study_year,80),graduation_year:c(b.graduation_year||b.doctor_graduation_year||b.resident_graduation_year||b.specialist_graduation_year,30),profession:c(b.profession,150),workplace:c(b.workplace,250),resident_specialty:c(b.resident_specialty||b.doctor_specialty||b.specialty,150),residency_year:c(b.residency_year,80),residency_hospital:c(b.residency_hospital,250),address:c(b.address,500),governorate:c(b.governorate,100),medlife_role:c(b.medlife_role,80),cell:c(b.cell,80),field_location:c(b.field_location,100),join_date:c(b.join_date,30),volunteer_certificate:c(b.volunteer_certificate,10)||'no'};
  const roles=['volunteer','supervisor','general_supervisor','assistant_supervisor'],cells=['plasma_cell','neuron_cell','astrocyte_cell','leukocyte_cell','heart_cell','red_blood_cell','blog','design','video_editing','visual_media','instagram','telegram','administration','voice_over','coordination','university_media','field'],fields=['damascus','aleppo','tartous','latakia','homs','hasakah'];
  if(!d.full_name||!d.mother_name||!d.national_id||!d.phone||!d.gender||!d.academic_status||!d.governorate||!d.medlife_role||!d.cell||!d.join_date)return out({success:false,error:'يرجى تعبئة جميع الحقول الأساسية المطلوبة.'},400);
  if(!['male','female'].includes(d.gender))return out({success:false,error:'الجنس المحدد غير صالح.'},400);if(!roles.includes(d.medlife_role))return out({success:false,error:'الصفة داخل MedLife غير صالحة.'},400);if(!cells.includes(d.cell))return out({success:false,error:'الخلية المحددة غير صالحة.'},400);if(!['yes','no'].includes(d.volunteer_certificate))return out({success:false,error:'قيمة شهادة التطوع غير صالحة.'},400);if(d.cell==='field'&&!fields.includes(d.field_location))return out({success:false,error:'يرجى اختيار المحافظة للعمل الميداني.'},400);if(d.cell!=='field'&&d.field_location)return out({success:false,error:'لا يمكن تحديد محافظة ميدانية إلا عند اختيار المجال الميداني.'},400);if(d.email&&!/^\S+@\S+\.\S+$/.test(d.email))return out({success:false,error:'البريد الإلكتروني غير صالح.'},400);
  await ensureColumns(env.MEMBERS_DB);
  const duplicate=await env.MEMBERS_DB.prepare('SELECT id FROM members WHERE national_id=? LIMIT 1').bind(d.national_id).first();if(duplicate)return out({success:false,error:'يوجد سجل سابق مرتبط بهذا الرقم الوطني. إذا كنت عضوًا مسجلًا أصلًا، تواصل مع الإدارة لتفعيل الحساب.'},409);
  const r=await env.MEMBERS_DB.prepare(`INSERT INTO members(full_name,mother_name,national_id,email,phone,gender,education_level,study_year,university,resident_specialty,residency_year,residency_hospital,address,governorate,medlife_role,cell,field_location,join_date,volunteer_certificate,status,created_at,updated_at,academic_status,faculty,graduation_year,profession,workplace) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'pending',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,?,?,?,?,?)`).bind(d.full_name,d.mother_name,d.national_id,d.email,d.phone,d.gender,d.education_level,d.study_year,d.university,d.resident_specialty,d.residency_year,d.residency_hospital,d.address,d.governorate,d.medlife_role,d.cell,d.cell==='field'?d.field_location:null,d.join_date,d.volunteer_certificate,d.academic_status,d.faculty,d.graduation_year,d.profession,d.workplace).run();
  return out({success:true,message:'تم استلام بيانات العضوية بنجاح، وستراجعها إدارة MedLife.',id:r.meta?.last_row_id??null,status:'pending'},201);
 }catch(e){console.error(e);return out({success:false,error:'تعذر إرسال بيانات العضوية حالياً.'},500)}
}
async function ensureColumns(db){const r=await db.prepare('PRAGMA table_info(members)').all();const have=new Set((r.results||[]).map(x=>x.name));const cols={academic_status:'TEXT',faculty:'TEXT',graduation_year:'TEXT',profession:'TEXT',workplace:'TEXT'};for(const [name,type] of Object.entries(cols)){if(!have.has(name))await db.prepare(`ALTER TABLE members ADD COLUMN ${name} ${type}`).run()}}
function out(data,status=200){return new Response(JSON.stringify(data,null,2),{status,headers:{'Content-Type':'application/json; charset=UTF-8','Cache-Control':'no-store','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'POST, OPTIONS'}})}
