/* MEDLIFE - NEW MEMBER APPLICATION
   POST /api/new-member
   New applicants are kept separate until administration approves them.
*/
import { hashPassword, json } from './_auth.js';
export async function onRequest({request,env}){
 if(request.method==='OPTIONS')return json({success:true});if(request.method!=='POST')return json({success:false,error:'Method not allowed.'},405);if(!env.MEMBERS_DB)return json({success:false,error:"Database binding 'MEMBERS_DB' is not configured."},500);
 try{
  const b=await request.json(),clean=(v,n=5000)=>String(v??'').trim().slice(0,n);
  const full_name=clean(b.full_name,150),mother_name=clean(b.mother_name,150),national_id=clean(b.national_id,40),gender=clean(b.gender,20),email=clean(b.email,200).toLowerCase(),phone=clean(b.phone,40),governorate=clean(b.governorate,100),address=clean(b.address,500),academic_status=clean(b.academic_status,30),interest=clean(b.interest,150),motivation=clean(b.motivation,2000),password=String(b.password||'');
  if(!full_name||!mother_name||!national_id||!gender||!email||!password||!phone||!governorate||!academic_status||!interest)return json({success:false,error:'يرجى تعبئة جميع الحقول الأساسية وإنشاء البريد وكلمة المرور.'},400);
  if(!['male','female'].includes(gender))return json({success:false,error:'الجنس المحدد غير صالح.'},400);if(!['student','graduate','doctor','resident','specialist','other'].includes(academic_status))return json({success:false,error:'الحالة الأكاديمية غير صالحة.'},400);if(!/^\S+@\S+\.\S+$/.test(email))return json({success:false,error:'البريد الإلكتروني غير صالح.'},400);if(password.length<8)return json({success:false,error:'يجب أن تتكون كلمة المرور من 8 أحرف/أرقام على الأقل.'},400);
  await env.MEMBERS_DB.prepare(`CREATE TABLE IF NOT EXISTS new_member_applications (id INTEGER PRIMARY KEY AUTOINCREMENT,full_name TEXT NOT NULL,mother_name TEXT NOT NULL,national_id TEXT NOT NULL UNIQUE,gender TEXT NOT NULL,email TEXT NOT NULL,account_password_hash TEXT NOT NULL,phone TEXT NOT NULL,governorate TEXT NOT NULL,address TEXT,academic_status TEXT NOT NULL,university TEXT,faculty TEXT,study_year TEXT,graduation_year TEXT,profession TEXT,workplace TEXT,resident_specialty TEXT,residency_year TEXT,residency_hospital TEXT,doctor_graduation_year TEXT,doctor_specialty TEXT,doctor_workplace TEXT,specialty TEXT,specialist_graduation_year TEXT,specialist_workplace TEXT,interest TEXT NOT NULL,motivation TEXT,status TEXT NOT NULL DEFAULT 'pending',rejection_reason TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();
  const cols=await env.MEMBERS_DB.prepare('PRAGMA table_info(new_member_applications)').all();const have=new Set((cols.results||[]).map(x=>x.name));if(!have.has('account_password_hash'))await env.MEMBERS_DB.prepare('ALTER TABLE new_member_applications ADD COLUMN account_password_hash TEXT').run();
  const exists=await env.MEMBERS_DB.prepare('SELECT id FROM new_member_applications WHERE national_id=? OR lower(email)=? LIMIT 1').bind(national_id,email).first();if(exists)return json({success:false,error:'يوجد طلب سابق مرتبط بالرقم الوطني أو البريد الإلكتروني.'},409);
  const fields=['university','faculty','study_year','graduation_year','profession','workplace','resident_specialty','residency_year','residency_hospital','doctor_graduation_year','doctor_specialty','doctor_workplace','specialty','specialist_graduation_year','specialist_workplace'];const vals=Object.fromEntries(fields.map(k=>[k,clean(b[k],250)]));const passwordHash=await hashPassword(password);
  const r=await env.MEMBERS_DB.prepare(`INSERT INTO new_member_applications (full_name,mother_name,national_id,gender,email,account_password_hash,phone,governorate,address,academic_status,university,faculty,study_year,graduation_year,profession,workplace,resident_specialty,residency_year,residency_hospital,doctor_graduation_year,doctor_specialty,doctor_workplace,specialty,specialist_graduation_year,specialist_workplace,interest,motivation) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(full_name,mother_name,national_id,gender,email,passwordHash,phone,governorate,address,academic_status,vals.university,vals.faculty,vals.study_year,vals.graduation_year,vals.profession,vals.workplace,vals.resident_specialty,vals.residency_year,vals.residency_hospital,vals.doctor_graduation_year,vals.doctor_specialty,vals.doctor_workplace,vals.specialty,vals.specialist_graduation_year,vals.specialist_workplace,interest,motivation).run();
  return json({success:true,id:r.meta?.last_row_id??null,status:'pending',message:'تم استلام طلب الانضمام وإنشاء بيانات الحساب. سيصبح الحساب فعالاً بعد موافقة الإدارة.'},201);
 }catch(e){console.error(e);return json({success:false,error:'تعذر إرسال طلب الانضمام حالياً.'},500)}
}
